li                  x24,    0x55fbc871
slli                x23,    x24,    27
sw                  x23,    355(x31)
li                  x22,    0x36e158f1
slli                x13,    x22,    15
sw                  x13,    1658(x31)
li                  x16,    0xbb13bc42
slli                x28,    x16,    27
sw                  x28,    2018(x31)
li                  x29,    0x80b756f0
srli                x18,    x29,    16
sw                  x18,    294(x31)
li                  x12,    0xf494d7c1
srli                x5,     x12,    21
sw                  x5,     2005(x31)
li                  x28,    0x13a844be
srli                x18,    x28,    15
sw                  x18,    0(x31)
li                  x31,    0xe121863f
srai                x20,    x31,    9
sw                  x20,    0(x31)
li                  x14,    0x4fa7d49c
srai                x13,    x14,    6
sw                  x13,    0(x31)
li                  x24,    0xa919b7e4
srai                x14,    x24,    0
sw                  x14,    1810(x31)
li                  x23,    0x13761d09
addi                x28,    x23,    -1729
sw                  x28,    0(x31)
li                  x2,     0xecf00f8f
addi                x26,    x2,     -1627
sw                  x26,    0(x31)
li                  x9,     0x1bbb48ab
addi                x21,    x9,     -1066
sw                  x21,    0(x31)
li                  x29,    0x1fdd873d
slti                x5,     x29,    -1002
sw                  x5,     0(x31)
li                  x8,     0xfc948168
slti                x19,    x8,     -449
sw                  x19,    0(x31)
li                  x6,     0x2d7d4ee1
slti                x27,    x6,     -73
sw                  x27,    1188(x31)
li                  x30,    0xe163b2e6
andi                x26,    x30,    361
sw                  x26,    279(x31)
li                  x16,    0x46cebfc
andi                x28,    x16,    884
sw                  x28,    0(x31)
li                  x23,    0x8c532649
andi                x4,     x23,    1744
sw                  x4,     0(x31)
li                  x14,    0xd4bfb18b
ori                 x17,    x14,    -1088
sw                  x17,    1588(x31)
li                  x20,    0x8c16f85f
ori                 x15,    x20,    -399
sw                  x15,    1461(x31)
li                  x31,    0xaee56d0c
ori                 x26,    x31,    806
sw                  x26,    931(x31)
li                  x31,    0xe056ab6e
xori                x9,     x31,    1683
sw                  x9,     1947(x31)
li                  x7,     0xa091bf36
xori                x8,     x7,     -1481
sw                  x8,     0(x31)
li                  x8,     0xff7342b2
xori                x16,    x8,     1569
sw                  x16,    499(x31)
li                  x3,     0xe79c1e5e
li                  x10,    0x78a369c8
add                 x10,    x3,     x10
sw                  x10,    0(x31)
li                  x9,     0xa8cbac7e
li                  x31,    0x702485ae
add                 x12,    x9,     x31
sw                  x12,    0(x31)
li                  x13,    0x6c7cc877
li                  x5,     0x3204484e
add                 x28,    x13,    x5
sw                  x28,    124(x31)
li                  x13,    0xd7f35879
li                  x27,    0xbf8c5af0
sub                 x14,    x13,    x27
sw                  x14,    0(x31)
li                  x11,    0x4926f107
li                  x28,    0x9309c732
sub                 x17,    x11,    x28
sw                  x17,    692(x31)
li                  x19,    0x2ce3a7ac
li                  x7,     0xba87f9eb
sub                 x16,    x19,    x7
sw                  x16,    0(x31)
li                  x3,     0x8ca81c29
li                  x15,    0x935ab3dd
mul                 x28,    x3,     x15
sw                  x28,    1420(x31)
li                  x29,    0x21e90ac5
li                  x16,    0xb16ae34a
mul                 x3,     x29,    x16
sw                  x3,     0(x31)
li                  x18,    0x96f88c03
li                  x16,    0xe27e6dd8
mul                 x7,     x18,    x16
sw                  x7,     0(x31)
li                  x15,    0xb12a2ffa
li                  x10,    0x5c393991
mulh                x6,     x15,    x10
sw                  x6,     1364(x31)
li                  x11,    0x67c4db35
li                  x28,    0xd98bfe1f
mulh                x14,    x11,    x28
sw                  x14,    0(x31)
li                  x26,    0x5dd9683d
li                  x24,    0xce1c69de
mulh                x13,    x26,    x24
sw                  x13,    380(x31)
li                  x10,    0x80e14acc
li                  x12,    0xbf00af56
mulhu               x5,     x10,    x12
sw                  x5,     519(x31)
li                  x8,     0x4829dbfb
li                  x29,    0xd354ab9f
mulhu               x17,    x8,     x29
sw                  x17,    0(x31)
li                  x23,    0xc8f594cb
li                  x10,    0x3f1bbb9c
mulhu               x18,    x23,    x10
sw                  x18,    0(x31)
li                  x5,     0x46c46650
li                  x12,    0xcf27c404
mulhsu              x1,     x5,     x12
sw                  x1,     0(x31)
li                  x19,    0x2891aaf6
li                  x21,    0x5310f383
mulhsu              x25,    x19,    x21
sw                  x25,    0(x31)
li                  x11,    0xd0beb1bb
li                  x27,    0x80c36c30
mulhsu              x20,    x11,    x27
sw                  x20,    1622(x31)
li                  x7,     0x35dcd39
li                  x29,    0x587cf520
div                 x25,    x7,     x29
sw                  x25,    1459(x31)
li                  x20,    0xc2058b25
li                  x27,    0x2f10f0f0
div                 x6,     x20,    x27
sw                  x6,     0(x31)
li                  x23,    0x6b49c088
li                  x23,    0xf6e17750
div                 x22,    x23,    x23
sw                  x22,    1594(x31)
li                  x12,    0x7f67f4f3
li                  x24,    0xe22b09ab
rem                 x15,    x12,    x24
sw                  x15,    1180(x31)
li                  x26,    0x889c9d6f
li                  x3,     0x53ce901d
rem                 x28,    x26,    x3
sw                  x28,    0(x31)
li                  x29,    0x248cf87a
li                  x29,    0x72a0df4e
rem                 x25,    x29,    x29
sw                  x25,    0(x31)
li                  x26,    0xfa1c62f2
li                  x4,     0x2a315e88
divu                x9,     x26,    x4
sw                  x9,     0(x31)
li                  x3,     0x1ef6c995
li                  x10,    0xf6cfd466
divu                x21,    x3,     x10
sw                  x21,    0(x31)
li                  x10,    0xbd253cbe
li                  x8,     0x6318e24a
divu                x15,    x10,    x8
sw                  x15,    1053(x31)
li                  x23,    0x2d255543
li                  x23,    0x32c59661
remu                x17,    x23,    x23
sw                  x17,    1613(x31)
li                  x27,    0x353edc8
li                  x1,     0xfe306096
remu                x16,    x27,    x1
sw                  x16,    389(x31)
li                  x24,    0xfef2194e
li                  x10,    0xa909d59c
remu                x14,    x24,    x10
sw                  x14,    737(x31)
li                  x14,    0x89744ff9
li                  x23,    0x841d6564
slt                 x18,    x14,    x23
sw                  x18,    1813(x31)
li                  x28,    0x9cad90c4
li                  x7,     0x529de07a
slt                 x30,    x28,    x7
sw                  x30,    103(x31)
li                  x13,    0x21e47592
li                  x4,     0x71849749
slt                 x29,    x13,    x4
sw                  x29,    1586(x31)
li                  x16,    0xb0a148b5
li                  x10,    0x4dbda8e6
sltu                x10,    x16,    x10
sw                  x10,    0(x31)
li                  x31,    0x27582c9a
li                  x3,     0xc74aafa8
sltu                x6,     x31,    x3
sw                  x6,     0(x31)
li                  x19,    0x68978ff0
li                  x10,    0x258bb0d9
sltu                x22,    x19,    x10
sw                  x22,    734(x31)

# Improve divider coverage
li                  x1,     962587531
li                  x2,     3604104759
li                  x3,     2999170505
li                  x4,     287361694
addi                x30,    x0,     30
lp.setup            x0,     x30,    div_loop
div                 x5,     x1,     x2
rem                 x6,     x1,     x2
divu                x7,     x3,     x4
remu                x8,     x3,     x4
add                 x1,     x1,     x5
or                  x2,     x2,     x6
sub                 x2,     x2,     x1
and                 x3,     x3,     x7
mul                 x3,     x3,     x2
xori                x4,     x4,     -1
slli                x4,     x4,     3
sub                 x4,     x4,     x15
sw                  x1,     4(x31)
sw                  x2,     4(x31)
sw                  x3,     4(x31)
sw                  x4,     4(x31)
sw                  x5,     4(x31)
sw                  x6,     4(x31)
sw                  x7,     4(x31)
sw                  x8,     4(x31)
div_loop:

# Divide by zero
div                 x1,     x0,     x0
sw                  x1,     0(x0)

# ALU extensions
li                  x0,     0xff171160
p.extract           x21,    x0,     9,      14
sw                  x21,    807(x31)
li                  x9,     0xfb217cf5
p.extract           x5,     x9,     2,      7
sw                  x5,     0(x31)
li                  x6,     0xbad62dc6
p.extract           x9,     x6,     23,     5
sw                  x9,     734(x31)
li                  x11,    0x4b86f10a
p.extractu          x18,    x11,    15,     13
sw                  x18,    1607(x31)
li                  x9,     0xc5f5892e
p.extractu          x11,    x9,     29,     13
sw                  x11,    0(x31)
li                  x27,    0x2225fda6
p.extractu          x2,     x27,    23,     19
sw                  x2,     1347(x31)
li                  x17,    0x5c23ea13
p.insert            x19,    x17,    16,     20
sw                  x19,    299(x31)
li                  x27,    0xa1495932
p.insert            x12,    x27,    16,     13
sw                  x12,    1833(x31)
li                  x26,    0x373f399e
p.insert            x9,     x26,    1,      3
sw                  x9,     1570(x31)
li                  x26,    0x271d58
p.bclr              x29,    x26,    26,     21
sw                  x29,    715(x31)
li                  x21,    0xaa58d5f9
p.bclr              x20,    x21,    1,      6
sw                  x20,    453(x31)
li                  x19,    0x47708983
p.bclr              x1,     x19,    20,     27
sw                  x1,     0(x31)
li                  x20,    0x32d09df2
p.bset              x19,    x20,    7,      26
sw                  x19,    0(x31)
li                  x5,     0xe70e2b06
p.bset              x14,    x5,     30,     27
sw                  x14,    0(x31)
li                  x31,    0x53c5a572
p.bset              x5,     x31,    21,     17
sw                  x5,     0(x31)
li                  x8,     0x94fec6b0
li                  x22,    0x8c18ad1a
p.extractr          x8,     x8,     x22
sw                  x8,     0(x31)
li                  x24,    0x234386b
li                  x15,    0xa607345
p.extractr          x26,    x24,    x15
sw                  x26,    0(x31)
li                  x17,    0xed166662
li                  x27,    0x36501625
p.extractr          x21,    x17,    x27
sw                  x21,    0(x31)
li                  x23,    0x1269b7cf
li                  x30,    0x4186ac7b
p.extractur         x6,     x23,    x30
sw                  x6,     1743(x31)
li                  x17,    0x73fffc6a
li                  x6,     0xf84983ae
p.extractur         x18,    x17,    x6
sw                  x18,    0(x31)
li                  x19,    0x1b304e0
li                  x30,    0xb3adc6bb
p.extractur         x29,    x19,    x30
sw                  x29,    1829(x31)
li                  x2,     0x40059761
li                  x2,     0x66f9565d
p.insertr           x1,     x2,     x2
sw                  x1,     865(x31)
li                  x3,     0x76dd56a6
li                  x22,    0xdb7ecc5a
p.insertr           x26,    x3,     x22
sw                  x26,    0(x31)
li                  x22,    0xce22d488
li                  x23,    0x3335a1ec
p.insertr           x21,    x22,    x23
sw                  x21,    0(x31)
li                  x18,    0x1096724b
li                  x19,    0x51be3436
p.bclrr             x20,    x18,    x19
sw                  x20,    1918(x31)
li                  x2,     0x55c0dfeb
li                  x8,     0xa0bd9dbf
p.bclrr             x23,    x2,     x8
sw                  x23,    0(x31)
li                  x31,    0x572a0cff
li                  x22,    0xe2aa260
p.bclrr             x7,     x31,    x22
sw                  x7,     1116(x31)
li                  x31,    0x5eaf534f
li                  x19,    0x811c5356
p.bsetr             x10,    x31,    x19
sw                  x10,    0(x31)
li                  x15,    0x811bd394
li                  x22,    0x238a215
p.bsetr             x22,    x15,    x22
sw                  x22,    0(x31)
li                  x17,    0xf6a5524f
li                  x11,    0x2c91df29
p.bsetr             x29,    x17,    x11
sw                  x29,    1825(x31)
li                  x22,    0x2ecc5bb5
li                  x13,    0x2dc07d2c
p.ror               x24,    x22,    x13
sw                  x24,    522(x31)
li                  x5,     0x560f6046
li                  x0,     0x9bd4befe
p.ror               x15,    x5,     x0
sw                  x15,    646(x31)
li                  x2,     0xc8544154
li                  x11,    0x9a279112
p.ror               x5,     x2,     x11
sw                  x5,     0(x31)
li                  x17,    0x8a8fd0a3
li                  x23,    0x96b75404
p.slet              x24,    x17,    x23
sw                  x24,    398(x31)
li                  x21,    0xdd8951fe
li                  x27,    0x9504ada9
p.slet              x5,     x21,    x27
sw                  x5,     0(x31)
li                  x1,     0x46e4ff34
li                  x12,    0x2956e8de
p.slet              x25,    x1,     x12
sw                  x25,    0(x31)
li                  x3,     0x14d7eb95
li                  x30,    0xb8cd5ab6
p.sletu             x5,     x3,     x30
sw                  x5,     1200(x31)
li                  x3,     0x5fd6c728
li                  x17,    0x1311733f
p.sletu             x30,    x3,     x17
sw                  x30,    1970(x31)
li                  x21,    0x998af542
li                  x12,    0xd153f5a7
p.sletu             x7,     x21,    x12
sw                  x7,     0(x31)
li                  x6,     0x31c0b794
li                  x30,    0x8b789ba3
p.min               x3,     x6,     x30
sw                  x3,     0(x31)
li                  x15,    0x8c441ecb
li                  x17,    0x1d9bfe62
p.min               x16,    x15,    x17
sw                  x16,    2007(x31)
li                  x29,    0xecc40991
li                  x12,    0x28598c7
p.min               x15,    x29,    x12
sw                  x15,    0(x31)
li                  x26,    0xe579779a
li                  x5,     0x23189a65
p.minu              x9,     x26,    x5
sw                  x9,     0(x31)
li                  x14,    0xa92d990c
li                  x1,     0x8954ed26
p.minu              x5,     x14,    x1
sw                  x5,     0(x31)
li                  x14,    0x6494e97a
li                  x12,    0x9956cfcf
p.minu              x22,    x14,    x12
sw                  x22,    0(x31)
li                  x3,     0x6a2a895c
li                  x27,    0x5b6ff78e
p.max               x12,    x3,     x27
sw                  x12,    376(x31)
li                  x20,    0x437ffc18
li                  x12,    0xc45d8be7
p.max               x1,     x20,    x12
sw                  x1,     1014(x31)
li                  x27,    0xed2f9a17
li                  x22,    0xea69fee1
p.max               x24,    x27,    x22
sw                  x24,    0(x31)
li                  x6,     0x516a4683
li                  x20,    0x3ca3d6e5
p.maxu              x4,     x6,     x20
sw                  x4,     1149(x31)
li                  x2,     0xd3332b61
li                  x7,     0xe2e48274
p.maxu              x14,    x2,     x7
sw                  x14,    0(x31)
li                  x5,     0x9de0687b
li                  x21,    0xaf83f602
p.maxu              x21,    x5,     x21
sw                  x21,    1848(x31)
li                  x23,    0x92007d97
li                  x1,     0xdc10538
p.clipr             x28,    x23,    x1
sw                  x28,    0(x31)
li                  x31,    0xbee1bc9e
li                  x15,    0x92d295ed
p.clipr             x29,    x31,    x15
sw                  x29,    215(x31)
li                  x29,    0x346edf2
li                  x6,     0xf7a29594
p.clipr             x24,    x29,    x6
sw                  x24,    0(x31)
li                  x9,     0x55c60ebd
li                  x3,     0x1bda43f8
p.clipur            x12,    x9,     x3
sw                  x12,    0(x31)
li                  x6,     0xc633400c
li                  x3,     0xb1adb957
p.clipur            x7,     x6,     x3
sw                  x7,     474(x31)
li                  x19,    0xdbddad36
li                  x28,    0x1c9590ca
p.clipur            x8,     x19,    x28
sw                  x8,     1342(x31)
li                  x28,    0x3e5aa713
li                  x21,    0x8b71360d
p.addNr             x25,    x28,    x21
sw                  x25,    1453(x31)
li                  x16,    0x4a8c375b
li                  x13,    0x1cf136d1
p.addNr             x27,    x16,    x13
sw                  x27,    0(x31)
li                  x3,     0x754bea77
li                  x2,     0xbd107444
p.addNr             x29,    x3,     x2
sw                  x29,    0(x31)
li                  x31,    0x9b9b6ad2
li                  x8,     0xe300d3b4
p.adduNr            x30,    x31,    x8
sw                  x30,    717(x31)
li                  x27,    0x47ed2b74
li                  x2,     0xe95e90b3
p.adduNr            x28,    x27,    x2
sw                  x28,    0(x31)
li                  x26,    0xe410d6
li                  x1,     0xacf4f7db
p.adduNr            x20,    x26,    x1
sw                  x20,    553(x31)
li                  x9,     0xa0ff408f
li                  x24,    0xeef203f1
p.addRNr            x25,    x9,     x24
sw                  x25,    0(x31)
li                  x4,     0xfb6f829f
li                  x30,    0x68aa71ba
p.addRNr            x12,    x4,     x30
sw                  x12,    0(x31)
li                  x11,    0xc78dc9fe
li                  x4,     0x2f7a7dc8
p.addRNr            x29,    x11,    x4
sw                  x29,    0(x31)
li                  x31,    0xab711c87
li                  x5,     0x9f122be4
p.adduRNr           x12,    x31,    x5
sw                  x12,    0(x31)
li                  x15,    0x84bb44aa
li                  x24,    0x241cef34
p.adduRNr           x28,    x15,    x24
sw                  x28,    781(x31)
li                  x15,    0xa04f068d
li                  x5,     0x79bee86e
p.adduRNr           x12,    x15,    x5
sw                  x12,    0(x31)
li                  x7,     0x9edcd640
li                  x17,    0xd2fdf71a
p.subNr             x8,     x7,     x17
sw                  x8,     0(x31)
li                  x27,    0xa3f67408
li                  x12,    0x664f0b54
p.subNr             x1,     x27,    x12
sw                  x1,     249(x31)
li                  x5,     0x34645988
li                  x21,    0xffa9d457
p.subNr             x8,     x5,     x21
sw                  x8,     1474(x31)
li                  x26,    0x7ff5037a
li                  x12,    0xf4edcd60
p.subuNr            x10,    x26,    x12
sw                  x10,    0(x31)
li                  x18,    0x4752fba6
li                  x23,    0x27ee37ae
p.subuNr            x17,    x18,    x23
sw                  x17,    1053(x31)
li                  x27,    0xd68aac1a
li                  x15,    0x2c4bdcbb
p.subuNr            x12,    x27,    x15
sw                  x12,    0(x31)
li                  x4,     0xc4c9421d
li                  x21,    0x6d293eca
p.subRNr            x20,    x4,     x21
sw                  x20,    0(x31)
li                  x26,    0xa51e542b
li                  x21,    0xc95371df
p.subRNr            x21,    x26,    x21
sw                  x21,    1782(x31)
li                  x16,    0x14fc6cf6
li                  x26,    0xfd6e69b
p.subRNr            x9,     x16,    x26
sw                  x9,     1921(x31)
li                  x11,    0x154d2f70
li                  x0,     0x90324be5
p.subuRNr           x25,    x11,    x0
sw                  x25,    0(x31)
li                  x25,    0xdcb6e813
li                  x12,    0x36116946
p.subuRNr           x4,     x25,    x12
sw                  x4,     0(x31)
li                  x9,     0xf4813212
li                  x20,    0xdceec518
p.subuRNr           x29,    x9,     x20
sw                  x29,    0(x31)
li                  x26,    0x7bc5aff6
li                  x18,    0xa3eff5df
p.mac               x18,    x26,    x18
sw                  x18,    0(x31)
li                  x28,    0x66f0c21e
li                  x2,     0x19061f0f
p.mac               x3,     x28,    x2
sw                  x3,     0(x31)
li                  x12,    0x3cfbaa07
li                  x12,    0x1845af45
p.mac               x1,     x12,    x12
sw                  x1,     0(x31)
li                  x22,    0x8b15a945
li                  x15,    0x113b0f86
p.msu               x28,    x22,    x15
sw                  x28,    0(x31)
li                  x14,    0x3f8bd87f
li                  x20,    0x6a7b9539
p.msu               x27,    x14,    x20
sw                  x27,    0(x31)
li                  x22,    0x6377fdc9
li                  x22,    0xecfb7398
p.msu               x22,    x22,    x22
sw                  x22,    0(x31)
li                  x18,    0x4176446e
li                  x8,     0x1d380810
p.muls              x14,    x18,    x8
sw                  x14,    779(x31)
li                  x11,    0xc80b0a89
li                  x31,    0x4662a471
p.muls              x13,    x11,    x31
sw                  x13,    0(x31)
li                  x26,    0x56395276
li                  x24,    0xaa232bdb
p.muls              x2,     x26,    x24
sw                  x2,     763(x31)
li                  x10,    0x2c0427a6
li                  x30,    0xff211b3
p.mulhhs            x5,     x10,    x30
sw                  x5,     1290(x31)
li                  x24,    0xee89ed39
li                  x7,     0x74b06a45
p.mulhhs            x20,    x24,    x7
sw                  x20,    554(x31)
li                  x6,     0xf1362af
li                  x6,     0xc9c28dcb
p.mulhhs            x22,    x6,     x6
sw                  x22,    694(x31)
li                  x18,    0x64d265a4
li                  x18,    0xc1eeac16
p.mulu              x27,    x18,    x18
sw                  x27,    833(x31)
li                  x14,    0xa6b6c1e6
li                  x25,    0x422002ca
p.mulu              x20,    x14,    x25
sw                  x20,    1199(x31)
li                  x5,     0xfdb7b4e
li                  x1,     0x90a6de84
p.mulu              x6,     x5,     x1
sw                  x6,     51(x31)
li                  x14,    0x740dcd0e
li                  x3,     0x345cb255
p.mulhhu            x28,    x14,    x3
sw                  x28,    435(x31)
li                  x8,     0x2e50fa23
li                  x1,     0x5988ffef
p.mulhhu            x8,     x8,     x1
sw                  x8,     0(x31)
li                  x2,     0x70aad266
li                  x14,    0xa7bed7a4
p.mulhhu            x19,    x2,     x14
sw                  x19,    0(x31)
li                  x10,    0xa7780098
p.ff1               x5,     x10
sw                  x5,     734(x31)
li                  x23,    0x55d56d94
p.ff1               x19,    x23
sw                  x19,    0(x31)
li                  x19,    0xe96fba3c
p.ff1               x10,    x19
sw                  x10,    0(x31)
li                  x3,     0x944e46da
p.fl1               x6,     x3
sw                  x6,     0(x31)
li                  x28,    0xaf2a7ee6
p.fl1               x19,    x28
sw                  x19,    0(x31)
li                  x2,     0x85019886
p.fl1               x22,    x2
sw                  x22,    768(x31)
li                  x4,     0x3f0104e6
p.clb               x8,     x4
sw                  x8,     0(x31)
li                  x21,    0xaa0c9160
p.clb               x17,    x21
sw                  x17,    1138(x31)
li                  x13,    0xabb882b0
p.clb               x27,    x13
sw                  x27,    0(x31)
li                  x7,     0xe1578797
p.cnt               x3,     x7
sw                  x3,     596(x31)
li                  x2,     0x1256cd52
p.cnt               x30,    x2
sw                  x30,    1363(x31)
li                  x8,     0x77f96dd
p.cnt               x16,    x8
sw                  x16,    0(x31)
li                  x11,    0x901d08d4
p.abs               x20,    x11
sw                  x20,    0(x31)
li                  x29,    0xd842357d
p.abs               x24,    x29
sw                  x24,    1270(x31)
li                  x11,    0x9124af3a
p.abs               x23,    x11
sw                  x23,    573(x31)
li                  x1,     0x24fe1792
p.exths             x22,    x1
sw                  x22,    1498(x31)
li                  x0,     0xd74683b0
p.exths             x5,     x0
sw                  x5,     932(x31)
li                  x26,    0x247e22db
p.exths             x22,    x26
sw                  x22,    0(x31)
li                  x14,    0xb1c2c76
p.exthz             x22,    x14
sw                  x22,    0(x31)
li                  x5,     0xde99478
p.exthz             x7,     x5
sw                  x7,     138(x31)
li                  x8,     0xe85e4ccb
p.exthz             x3,     x8
sw                  x3,     676(x31)
li                  x22,    0xf8b2e05
p.extbs             x11,    x22
sw                  x11,    0(x31)
li                  x22,    0x9ff68466
p.extbs             x14,    x22
sw                  x14,    1083(x31)
li                  x5,     0x9f7b5714
p.extbs             x13,    x5
sw                  x13,    673(x31)
li                  x30,    0x3f372048
p.extbz             x1,     x30
sw                  x1,     0(x31)
li                  x2,     0x80132e6
p.extbz             x19,    x2
sw                  x19,    0(x31)
li                  x12,    0x48020963
p.extbz             x19,    x12
sw                  x19,    0(x31)
li                  x8,     0xb3f828c9
p.clip              x1,     x8,     25
sw                  x1,     1427(x31)
li                  x26,    0x66b4f28b
p.clip              x16,    x26,    21
sw                  x16,    1115(x31)
li                  x11,    0x94509e21
p.clip              x14,    x11,    31
sw                  x14,    1224(x31)
li                  x11,    0x212e048b
p.clipu             x14,    x11,    4
sw                  x14,    2019(x31)
li                  x25,    0x2734fdd6
p.clipu             x6,     x25,    1
sw                  x6,     0(x31)
li                  x3,     0x19f015be
p.clipu             x5,     x3,     23
sw                  x5,     0(x31)
p.addN              x23,    x4,     x2,     11
sw                  x23,    977(x31)
p.addN              x24,    x18,    x26,    11
sw                  x24,    0(x31)
p.addN              x15,    x1,     x20,    2
sw                  x15,    0(x31)
p.adduN             x7,     x15,    x9,     25
sw                  x7,     0(x31)
p.adduN             x22,    x11,    x24,    30
sw                  x22,    912(x31)
p.adduN             x25,    x3,     x14,    1
sw                  x25,    0(x31)
p.addRN             x4,     x22,    x0,     24
sw                  x4,     0(x31)
p.addRN             x3,     x24,    x0,     22
sw                  x3,     0(x31)
p.addRN             x12,    x10,    x9,     25
sw                  x12,    1037(x31)
p.adduRN            x27,    x5,     x27,    26
sw                  x27,    0(x31)
p.adduRN            x19,    x8,     x12,    21
sw                  x19,    1676(x31)
p.adduRN            x17,    x28,    x23,    23
sw                  x17,    683(x31)
p.subN              x11,    x24,    x8,     25
sw                  x11,    0(x31)
p.subN              x5,     x2,     x12,    2
sw                  x5,     0(x31)
p.subN              x28,    x3,     x6,     4
sw                  x28,    0(x31)
p.subuN             x10,    x28,    x1,     9
sw                  x10,    0(x31)
p.subuN             x15,    x27,    x17,    1
sw                  x15,    982(x31)
p.subuN             x20,    x10,    x7,     26
sw                  x20,    611(x31)
p.subRN             x14,    x21,    x17,    0
sw                  x14,    0(x31)
p.subRN             x17,    x7,     x2,     6
sw                  x17,    1102(x31)
p.subRN             x2,     x14,    x13,    29
sw                  x2,     0(x31)
p.subuRN            x7,     x31,    x17,    21
sw                  x7,     0(x31)
p.subuRN            x5,     x18,    x7,     13
sw                  x5,     0(x31)
p.subuRN            x25,    x13,    x2,     0
sw                  x25,    0(x31)
p.mulsN             x10,    x15,    x8,     22
sw                  x10,    642(x31)
p.mulsN             x25,    x6,     x27,    28
sw                  x25,    0(x31)
p.mulsN             x1,     x7,     x10,    15
sw                  x1,     1785(x31)
p.mulhhsN           x19,    x3,     x17,    26
sw                  x19,    1175(x31)
p.mulhhsN           x2,     x9,     x17,    3
sw                  x2,     0(x31)
p.mulhhsN           x24,    x19,    x7,     1
sw                  x24,    1099(x31)
p.mulsRN            x29,    x23,    x4,     0
sw                  x29,    328(x31)
p.mulsRN            x15,    x20,    x9,     29
sw                  x15,    0(x31)
p.mulsRN            x3,     x17,    x11,    14
sw                  x3,     0(x31)
p.mulhhsRN          x18,    x21,    x21,    9
sw                  x18,    942(x31)
p.mulhhsRN          x22,    x0,     x29,    0
sw                  x22,    0(x31)
p.mulhhsRN          x16,    x21,    x26,    2
sw                  x16,    1683(x31)
p.muluN             x24,    x13,    x10,    20
sw                  x24,    0(x31)
p.muluN             x13,    x12,    x26,    4
sw                  x13,    0(x31)
p.muluN             x25,    x1,     x16,    30
sw                  x25,    18(x31)
p.mulhhuN           x25,    x8,     x26,    15
sw                  x25,    0(x31)
p.mulhhuN           x3,     x31,    x19,    25
sw                  x3,     1512(x31)
p.mulhhuN           x7,     x23,    x25,    19
sw                  x7,     1819(x31)
p.muluRN            x21,    x25,    x5,     20
sw                  x21,    1392(x31)
p.muluRN            x29,    x16,    x31,    12
sw                  x29,    1999(x31)
p.muluRN            x27,    x11,    x7,     1
sw                  x27,    0(x31)
p.mulhhuRN          x22,    x5,     x31,    26
sw                  x22,    0(x31)
p.mulhhuRN          x10,    x2,     x20,    17
sw                  x10,    980(x31)
p.mulhhuRN          x11,    x27,    x4,     26
sw                  x11,    1565(x31)
p.macsN             x20,    x27,    x13,    26
sw                  x20,    20(x31)
p.macsN             x22,    x12,    x13,    18
sw                  x22,    0(x31)
p.macsN             x17,    x12,    x9,     24
sw                  x17,    1101(x31)
p.machhsN           x14,    x31,    x2,     16
sw                  x14,    805(x31)
p.machhsN           x9,     x12,    x0,     15
sw                  x9,     1625(x31)
p.machhsN           x23,    x5,     x3,     30
sw                  x23,    1819(x31)
p.macsRN            x29,    x1,     x13,    31
sw                  x29,    865(x31)
p.macsRN            x17,    x29,    x13,    5
sw                  x17,    93(x31)
p.macsRN            x6,     x14,    x24,    26
sw                  x6,     1149(x31)
p.machhsRN          x29,    x10,    x31,    5
sw                  x29,    0(x31)
p.machhsRN          x23,    x29,    x22,    4
sw                  x23,    0(x31)
p.machhsRN          x11,    x14,    x19,    9
sw                  x11,    0(x31)
p.macuN             x24,    x9,     x10,    11
sw                  x24,    321(x31)
p.macuN             x24,    x16,    x19,    11
sw                  x24,    0(x31)
p.macuN             x21,    x29,    x1,     7
sw                  x21,    1125(x31)
p.machhuN           x19,    x18,    x27,    27
sw                  x19,    0(x31)
p.machhuN           x29,    x15,    x13,    16
sw                  x29,    0(x31)
p.machhuN           x5,     x7,     x23,    3
sw                  x5,     7(x31)
p.macuRN            x19,    x2,     x0,     30
sw                  x19,    1121(x31)
p.macuRN            x14,    x7,     x18,    1
sw                  x14,    0(x31)
p.macuRN            x26,    x11,    x26,    7
sw                  x26,    1261(x31)
p.machhuRN          x19,    x19,    x15,    5
sw                  x19,    0(x31)
p.machhuRN          x12,    x23,    x12,    14
sw                  x12,    0(x31)
p.machhuRN          x27,    x0,     x26,    20
sw                  x27,    1403(x31)

# Vector operations
li                  x27,    0x3cd0c55b
li                  x31,    0x4143c044
pv.add.h            x4,     x27,    x31
sw                  x4,     1200(x31)
li                  x7,     0x76283ae2
li                  x25,    0x47d9b2f6
pv.add.h            x10,    x7,     x25
sw                  x10,    1853(x31)
li                  x29,    0x6d0aa1c0
li                  x18,    0xf7717b21
pv.add.h            x30,    x29,    x18
sw                  x30,    1152(x31)
li                  x7,     0xbd02b8b5
li                  x14,    0x255287d1
pv.add.b            x6,     x7,     x14
sw                  x6,     0(x31)
li                  x25,    0xbe3f06c0
li                  x7,     0x36cf9b23
pv.add.b            x18,    x25,    x7
sw                  x18,    0(x31)
li                  x8,     0x53e3993c
li                  x22,    0x9a3c6649
pv.add.b            x22,    x8,     x22
sw                  x22,    474(x31)
li                  x0,     0x8feb0760
li                  x23,    0x22bf602e
pv.add.sc.h         x18,    x0,     x23
sw                  x18,    0(x31)
li                  x24,    0x7f686cf1
li                  x17,    0xffbc68fd
pv.add.sc.h         x1,     x24,    x17
sw                  x1,     0(x31)
li                  x12,    0x1ce5febe
li                  x11,    0xb3b00a90
pv.add.sc.h         x26,    x12,    x11
sw                  x26,    926(x31)
li                  x23,    0x4559dd5e
li                  x8,     0xe975b6ed
pv.add.sc.b         x1,     x23,    x8
sw                  x1,     98(x31)
li                  x16,    0xa5d9882a
li                  x5,     0x37d878c2
pv.add.sc.b         x2,     x16,    x5
sw                  x2,     0(x31)
li                  x19,    0x974c7ad4
li                  x21,    0x1e08a591
pv.add.sc.b         x15,    x19,    x21
sw                  x15,    739(x31)
li                  x10,    0x8334e395
pv.add.sci.h        x26,    x10,    11
sw                  x26,    0(x31)
li                  x2,     0x12eb4655
pv.add.sci.h        x18,    x2,     12
sw                  x18,    14(x31)
li                  x4,     0x76d2fe47
pv.add.sci.h        x12,    x4,     30
sw                  x12,    1122(x31)
li                  x15,    0x305e0bb8
pv.add.sci.b        x20,    x15,    16
sw                  x20,    0(x31)
li                  x21,    0x78f82465
pv.add.sci.b        x5,     x21,    30
sw                  x5,     0(x31)
li                  x15,    0x1124ab50
pv.add.sci.b        x10,    x15,    14
sw                  x10,    0(x31)
li                  x4,     0xc80f238e
li                  x20,    0xb13d839f
pv.sub.h            x4,     x4,     x20
sw                  x4,     700(x31)
li                  x2,     0x96820981
li                  x11,    0x43629eb3
pv.sub.h            x27,    x2,     x11
sw                  x27,    0(x31)
li                  x21,    0x794d3ddc
li                  x14,    0x171ed119
pv.sub.h            x11,    x21,    x14
sw                  x11,    1942(x31)
li                  x27,    0x5f347d4
li                  x19,    0xac722020
pv.sub.b            x28,    x27,    x19
sw                  x28,    0(x31)
li                  x0,     0x9cb4731b
li                  x24,    0x51fbd34c
pv.sub.b            x19,    x0,     x24
sw                  x19,    0(x31)
li                  x26,    0x2f279e9c
li                  x18,    0xfc9a3294
pv.sub.b            x27,    x26,    x18
sw                  x27,    0(x31)
li                  x28,    0x701c384d
li                  x10,    0x23d66a38
pv.sub.sc.h         x25,    x28,    x10
sw                  x25,    295(x31)
li                  x29,    0xfa2993e
li                  x24,    0xe23814c1
pv.sub.sc.h         x19,    x29,    x24
sw                  x19,    80(x31)
li                  x8,     0xe0d89fb3
li                  x15,    0x68002397
pv.sub.sc.h         x7,     x8,     x15
sw                  x7,     0(x31)
li                  x21,    0xb106bf72
li                  x12,    0x3381af94
pv.sub.sc.b         x6,     x21,    x12
sw                  x6,     1721(x31)
li                  x1,     0x2cec8461
li                  x9,     0x9a05481
pv.sub.sc.b         x6,     x1,     x9
sw                  x6,     0(x31)
li                  x25,    0x7fa609a5
li                  x7,     0xccf2661f
pv.sub.sc.b         x30,    x25,    x7
sw                  x30,    1665(x31)
li                  x19,    0x7cb9f927
pv.sub.sci.h        x25,    x19,    27
sw                  x25,    1028(x31)
li                  x23,    0xfde26fa8
pv.sub.sci.h        x28,    x23,    21
sw                  x28,    1733(x31)
li                  x16,    0xd74fe961
pv.sub.sci.h        x10,    x16,    21
sw                  x10,    1205(x31)
li                  x16,    0xade486b1
pv.sub.sci.b        x28,    x16,    1
sw                  x28,    0(x31)
li                  x3,     0x7d6aa43f
pv.sub.sci.b        x14,    x3,     31
sw                  x14,    0(x31)
li                  x11,    0x1dc4fc4a
pv.sub.sci.b        x26,    x11,    13
sw                  x26,    0(x31)
li                  x4,     0x96ae622d
li                  x5,     0xa3b640f6
pv.avg.h            x16,    x4,     x5
sw                  x16,    0(x31)
li                  x30,    0xe98d6d9b
li                  x12,    0x96992324
pv.avg.h            x12,    x30,    x12
sw                  x12,    972(x31)
li                  x26,    0x2c8a4227
li                  x6,     0xd07c40ab
pv.avg.h            x30,    x26,    x6
sw                  x30,    1593(x31)
li                  x6,     0xe3f32aaf
li                  x3,     0xcefee141
pv.avg.b            x22,    x6,     x3
sw                  x22,    1185(x31)
li                  x27,    0x1e9ec6dc
li                  x27,    0x67925362
pv.avg.b            x6,     x27,    x27
sw                  x6,     0(x31)
li                  x13,    0x26ed5c7c
li                  x19,    0x85869bfa
pv.avg.b            x19,    x13,    x19
sw                  x19,    0(x31)
li                  x21,    0x92cbe666
li                  x22,    0xd874b747
pv.avg.sc.h         x14,    x21,    x22
sw                  x14,    414(x31)
li                  x24,    0xcb19370e
li                  x3,     0x4cbf5150
pv.avg.sc.h         x24,    x24,    x3
sw                  x24,    1525(x31)
li                  x12,    0x6c02ced7
li                  x15,    0xa0248d5b
pv.avg.sc.h         x23,    x12,    x15
sw                  x23,    851(x31)
li                  x16,    0x6c08cba2
li                  x27,    0xf6beb8c3
pv.avg.sc.b         x9,     x16,    x27
sw                  x9,     0(x31)
li                  x7,     0x4b64f604
li                  x13,    0xa17b545c
pv.avg.sc.b         x20,    x7,     x13
sw                  x20,    0(x31)
li                  x17,    0x69f3be34
li                  x31,    0x4822056a
pv.avg.sc.b         x12,    x17,    x31
sw                  x12,    628(x31)
li                  x0,     0xafe5a18c
pv.avg.sci.h        x8,     x0,     8
sw                  x8,     584(x31)
li                  x28,    0xcd1a8a9a
pv.avg.sci.h        x10,    x28,    2
sw                  x10,    0(x31)
li                  x6,     0x77f77300
pv.avg.sci.h        x4,     x6,     0
sw                  x4,     0(x31)
li                  x17,    0x40385864
pv.avg.sci.b        x13,    x17,    18
sw                  x13,    0(x31)
li                  x8,     0xfb22b0ee
pv.avg.sci.b        x16,    x8,     21
sw                  x16,    0(x31)
li                  x7,     0x2d0494fe
pv.avg.sci.b        x29,    x7,     10
sw                  x29,    0(x31)
li                  x1,     0x598cbe92
li                  x4,     0xe73d37b9
pv.avgu.h           x25,    x1,     x4
sw                  x25,    0(x31)
li                  x9,     0x3e5b8541
li                  x13,    0xfe49a6a8
pv.avgu.h           x21,    x9,     x13
sw                  x21,    1162(x31)
li                  x23,    0x66ae8765
li                  x6,     0x25cf388f
pv.avgu.h           x23,    x23,    x6
sw                  x23,    0(x31)
li                  x21,    0xb6a22cd3
li                  x6,     0x8bb09b37
pv.avgu.b           x12,    x21,    x6
sw                  x12,    1502(x31)
li                  x23,    0xd5cecd40
li                  x7,     0xea71ea3d
pv.avgu.b           x15,    x23,    x7
sw                  x15,    501(x31)
li                  x13,    0xb9588ef6
li                  x19,    0x3f7a1b0e
pv.avgu.b           x30,    x13,    x19
sw                  x30,    1200(x31)
li                  x20,    0x9f4c9030
li                  x0,     0xfc36e3ae
pv.avgu.sc.h        x6,     x20,    x0
sw                  x6,     795(x31)
li                  x17,    0x7c0ffd31
li                  x3,     0x77a4ae6b
pv.avgu.sc.h        x14,    x17,    x3
sw                  x14,    0(x31)
li                  x21,    0x48cf8a
li                  x19,    0x3daf1053
pv.avgu.sc.h        x22,    x21,    x19
sw                  x22,    0(x31)
li                  x9,     0x56e02f0b
li                  x12,    0xcdeae233
pv.avgu.sc.b        x21,    x9,     x12
sw                  x21,    1800(x31)
li                  x1,     0x3b59b376
li                  x5,     0x92ad730d
pv.avgu.sc.b        x19,    x1,     x5
sw                  x19,    0(x31)
li                  x1,     0xe7e4671f
li                  x17,    0xacc71d66
pv.avgu.sc.b        x19,    x1,     x17
sw                  x19,    0(x31)
li                  x19,    0x9b24471f
pv.avgu.sci.h       x3,     x19,    9
sw                  x3,     0(x31)
li                  x25,    0xf867bd9f
pv.avgu.sci.h       x5,     x25,    11
sw                  x5,     0(x31)
li                  x24,    0xf3e913b1
pv.avgu.sci.h       x19,    x24,    26
sw                  x19,    0(x31)
li                  x2,     0x4fc63912
pv.avgu.sci.b       x21,    x2,     12
sw                  x21,    1407(x31)
li                  x6,     0x670a19de
pv.avgu.sci.b       x5,     x6,     2
sw                  x5,     1349(x31)
li                  x4,     0xef43a537
pv.avgu.sci.b       x20,    x4,     6
sw                  x20,    376(x31)
li                  x31,    0xf0a45058
li                  x21,    0xaec4efa7
pv.min.h            x23,    x31,    x21
sw                  x23,    626(x31)
li                  x25,    0xf711ed66
li                  x31,    0xdcbc7b76
pv.min.h            x5,     x25,    x31
sw                  x5,     169(x31)
li                  x1,     0x61b7c731
li                  x5,     0x44589d70
pv.min.h            x11,    x1,     x5
sw                  x11,    0(x31)
li                  x28,    0x8e83a144
li                  x16,    0x1f272168
pv.min.b            x14,    x28,    x16
sw                  x14,    591(x31)
li                  x19,    0x4ed767a7
li                  x6,     0xccea0322
pv.min.b            x25,    x19,    x6
sw                  x25,    0(x31)
li                  x29,    0x15113fad
li                  x27,    0xbb3a92fd
pv.min.b            x29,    x29,    x27
sw                  x29,    0(x31)
li                  x7,     0x97b365da
li                  x16,    0xf83de5f7
pv.min.sc.h         x24,    x7,     x16
sw                  x24,    930(x31)
li                  x28,    0xbaa7aeee
li                  x30,    0xb2992b62
pv.min.sc.h         x20,    x28,    x30
sw                  x20,    410(x31)
li                  x28,    0xe9883a47
li                  x3,     0x6f034a22
pv.min.sc.h         x25,    x28,    x3
sw                  x25,    1395(x31)
li                  x6,     0xcf8074c3
li                  x2,     0xb3789993
pv.min.sc.b         x9,     x6,     x2
sw                  x9,     0(x31)
li                  x9,     0xc4ab6064
li                  x26,    0xee457b0d
pv.min.sc.b         x13,    x9,     x26
sw                  x13,    1492(x31)
li                  x8,     0xb74d0327
li                  x20,    0x9d83aec3
pv.min.sc.b         x6,     x8,     x20
sw                  x6,     0(x31)
li                  x13,    0xe14975e0
pv.min.sci.h        x14,    x13,    29
sw                  x14,    1976(x31)
li                  x17,    0xb0d33ee5
pv.min.sci.h        x6,     x17,    15
sw                  x6,     0(x31)
li                  x15,    0xd6e76002
pv.min.sci.h        x23,    x15,    0
sw                  x23,    0(x31)
li                  x25,    0x46cec612
pv.min.sci.b        x25,    x25,    24
sw                  x25,    1032(x31)
li                  x10,    0x1f81e7b3
pv.min.sci.b        x9,     x10,    2
sw                  x9,     334(x31)
li                  x14,    0xd096da95
pv.min.sci.b        x9,     x14,    27
sw                  x9,     0(x31)
li                  x8,     0xbc44e483
li                  x11,    0x26894e8d
pv.minu.h           x27,    x8,     x11
sw                  x27,    0(x31)
li                  x4,     0xf3c7edd0
li                  x28,    0xd603d59
pv.minu.h           x10,    x4,     x28
sw                  x10,    933(x31)
li                  x29,    0x9f084e7
li                  x13,    0x62bd42ff
pv.minu.h           x8,     x29,    x13
sw                  x8,     0(x31)
li                  x14,    0xf3b30e78
li                  x4,     0x89aaccf8
pv.minu.b           x11,    x14,    x4
sw                  x11,    1697(x31)
li                  x22,    0xd5466c57
li                  x28,    0xb1c3e6b4
pv.minu.b           x1,     x22,    x28
sw                  x1,     0(x31)
li                  x14,    0xca32d3bd
li                  x22,    0xe3898f70
pv.minu.b           x16,    x14,    x22
sw                  x16,    787(x31)
li                  x17,    0x69906eda
li                  x2,     0xa738689b
pv.minu.sc.h        x12,    x17,    x2
sw                  x12,    1958(x31)
li                  x30,    0x14740cd6
li                  x13,    0x3e575847
pv.minu.sc.h        x25,    x30,    x13
sw                  x25,    1997(x31)
li                  x7,     0xc5ca714e
li                  x1,     0x76e3e65a
pv.minu.sc.h        x10,    x7,     x1
sw                  x10,    1485(x31)
li                  x17,    0xf12d62af
li                  x4,     0x12217a53
pv.minu.sc.b        x16,    x17,    x4
sw                  x16,    100(x31)
li                  x30,    0x14be7b9a
li                  x10,    0x14b6cf90
pv.minu.sc.b        x26,    x30,    x10
sw                  x26,    124(x31)
li                  x24,    0x35dce18d
li                  x14,    0x97ae70f5
pv.minu.sc.b        x5,     x24,    x14
sw                  x5,     0(x31)
li                  x20,    0xd7a1a67d
pv.minu.sci.h       x26,    x20,    13
sw                  x26,    1277(x31)
li                  x21,    0xef92df2c
pv.minu.sci.h       x5,     x21,    13
sw                  x5,     0(x31)
li                  x25,    0x6544b8b
pv.minu.sci.h       x2,     x25,    19
sw                  x2,     0(x31)
li                  x29,    0xa8f3a877
pv.minu.sci.b       x24,    x29,    0
sw                  x24,    2010(x31)
li                  x4,     0x57f4145d
pv.minu.sci.b       x19,    x4,     23
sw                  x19,    0(x31)
li                  x16,    0x97561ac2
pv.minu.sci.b       x8,     x16,    30
sw                  x8,     724(x31)
li                  x31,    0x8e41e187
li                  x30,    0x548a5f92
pv.max.h            x19,    x31,    x30
sw                  x19,    278(x31)
li                  x29,    0x16e1cc6e
li                  x24,    0x59e2e2aa
pv.max.h            x25,    x29,    x24
sw                  x25,    1954(x31)
li                  x10,    0x2ac8a73b
li                  x2,     0x6118d3a2
pv.max.h            x20,    x10,    x2
sw                  x20,    570(x31)
li                  x15,    0xfb2baf32
li                  x23,    0xb5d8414e
pv.max.b            x30,    x15,    x23
sw                  x30,    408(x31)
li                  x22,    0x59404266
li                  x19,    0x60c5d2f6
pv.max.b            x11,    x22,    x19
sw                  x11,    0(x31)
li                  x24,    0x476e16c2
li                  x19,    0x10d0c595
pv.max.b            x13,    x24,    x19
sw                  x13,    0(x31)
li                  x4,     0x52c6f800
li                  x16,    0x49fee733
pv.max.sc.h         x30,    x4,     x16
sw                  x30,    2025(x31)
li                  x20,    0x2ce3c701
li                  x23,    0x98a9e2e0
pv.max.sc.h         x13,    x20,    x23
sw                  x13,    52(x31)
li                  x8,     0x2b404db1
li                  x4,     0x30967abc
pv.max.sc.h         x18,    x8,     x4
sw                  x18,    880(x31)
li                  x3,     0xaa7db299
li                  x15,    0x9ffd61f3
pv.max.sc.b         x11,    x3,     x15
sw                  x11,    0(x31)
li                  x18,    0x81497c8
li                  x23,    0x919642ff
pv.max.sc.b         x18,    x18,    x23
sw                  x18,    0(x31)
li                  x3,     0x4c2c720a
li                  x8,     0xf4722c7c
pv.max.sc.b         x27,    x3,     x8
sw                  x27,    0(x31)
li                  x20,    0x67b8d56e
pv.max.sci.h        x1,     x20,    13
sw                  x1,     0(x31)
li                  x25,    0x146db92a
pv.max.sci.h        x3,     x25,    8
sw                  x3,     1611(x31)
li                  x29,    0x25ebdb46
pv.max.sci.h        x24,    x29,    9
sw                  x24,    0(x31)
li                  x9,     0xcfb49c9d
pv.max.sci.b        x3,     x9,     6
sw                  x3,     1231(x31)
li                  x16,    0x3dc6a97
pv.max.sci.b        x9,     x16,    22
sw                  x9,     1415(x31)
li                  x21,    0xaaf21a01
pv.max.sci.b        x11,    x21,    22
sw                  x11,    700(x31)
li                  x23,    0x519238f4
li                  x2,     0xe19fcc8c
pv.maxu.h           x28,    x23,    x2
sw                  x28,    1342(x31)
li                  x21,    0xa4cdf1bb
li                  x4,     0x1f45a7d4
pv.maxu.h           x19,    x21,    x4
sw                  x19,    0(x31)
li                  x22,    0xb3bd3363
li                  x10,    0xbd116228
pv.maxu.h           x4,     x22,    x10
sw                  x4,     974(x31)
li                  x26,    0x63fe6bd6
li                  x16,    0xd1f4fe2c
pv.maxu.b           x7,     x26,    x16
sw                  x7,     737(x31)
li                  x7,     0x8ed7d435
li                  x11,    0xde6513aa
pv.maxu.b           x25,    x7,     x11
sw                  x25,    0(x31)
li                  x27,    0xada0089b
li                  x1,     0xf7fef212
pv.maxu.b           x20,    x27,    x1
sw                  x20,    0(x31)
li                  x3,     0x9cb4a9d2
li                  x20,    0xc3b29ecd
pv.maxu.sc.h        x26,    x3,     x20
sw                  x26,    0(x31)
li                  x2,     0x1e2c8c7b
li                  x6,     0xbb0ccac0
pv.maxu.sc.h        x30,    x2,     x6
sw                  x30,    32(x31)
li                  x23,    0xfd8577d4
li                  x10,    0x7ee0185d
pv.maxu.sc.h        x27,    x23,    x10
sw                  x27,    1508(x31)
li                  x27,    0xbcbe186b
li                  x20,    0x8602f
pv.maxu.sc.b        x28,    x27,    x20
sw                  x28,    1922(x31)
li                  x25,    0x6400825c
li                  x17,    0x804b34c6
pv.maxu.sc.b        x9,     x25,    x17
sw                  x9,     0(x31)
li                  x6,     0x640f58e6
li                  x18,    0x93824a9d
pv.maxu.sc.b        x21,    x6,     x18
sw                  x21,    0(x31)
li                  x30,    0xf1943da0
pv.maxu.sci.h       x19,    x30,    19
sw                  x19,    0(x31)
li                  x8,     0xe8b25e79
pv.maxu.sci.h       x20,    x8,     15
sw                  x20,    0(x31)
li                  x17,    0x49457b2a
pv.maxu.sci.h       x11,    x17,    30
sw                  x11,    372(x31)
li                  x12,    0x79aebe7e
pv.maxu.sci.b       x25,    x12,    31
sw                  x25,    0(x31)
li                  x15,    0x2657a8de
pv.maxu.sci.b       x19,    x15,    11
sw                  x19,    0(x31)
li                  x12,    0x4e70ae17
pv.maxu.sci.b       x19,    x12,    18
sw                  x19,    2014(x31)
li                  x31,    0xa3f219b9
li                  x14,    0xdb5d0064
pv.srl.h            x7,     x31,    x14
sw                  x7,     1291(x31)
li                  x10,    0xf5b5738d
li                  x25,    0x657910b2
pv.srl.h            x20,    x10,    x25
sw                  x20,    41(x31)
li                  x15,    0x451eeb74
li                  x8,     0x92deac6
pv.srl.h            x4,     x15,    x8
sw                  x4,     1396(x31)
li                  x2,     0x154be70b
li                  x6,     0x76a02b6e
pv.srl.b            x22,    x2,     x6
sw                  x22,    1800(x31)
li                  x9,     0xb414c111
li                  x19,    0x88eb581e
pv.srl.b            x4,     x9,     x19
sw                  x4,     0(x31)
li                  x9,     0x9282ee67
li                  x25,    0xca4f7d2d
pv.srl.b            x23,    x9,     x25
sw                  x23,    0(x31)
li                  x12,    0x43044676
li                  x24,    0x3bc98779
pv.srl.sc.h         x17,    x12,    x24
sw                  x17,    0(x31)
li                  x25,    0xfc2bdd95
li                  x18,    0x8655d2cc
pv.srl.sc.h         x10,    x25,    x18
sw                  x10,    0(x31)
li                  x12,    0xc012467c
li                  x31,    0x2e1abbc9
pv.srl.sc.h         x3,     x12,    x31
sw                  x3,     555(x31)
li                  x27,    0x55aabd7d
li                  x21,    0xbd5033e8
pv.srl.sc.b         x24,    x27,    x21
sw                  x24,    0(x31)
li                  x27,    0x4833bf27
li                  x8,     0xc6370f6
pv.srl.sc.b         x9,     x27,    x8
sw                  x9,     0(x31)
li                  x30,    0xeb0a2441
li                  x5,     0x313b2da7
pv.srl.sc.b         x14,    x30,    x5
sw                  x14,    0(x31)
li                  x12,    0x5d8169f8
pv.srl.sci.h        x19,    x12,    12
sw                  x19,    938(x31)
li                  x0,     0xb808bc1
pv.srl.sci.h        x25,    x0,     27
sw                  x25,    0(x31)
li                  x7,     0x2465a5e8
pv.srl.sci.h        x11,    x7,     2
sw                  x11,    1527(x31)
li                  x20,    0xcea81127
pv.srl.sci.b        x24,    x20,    5
sw                  x24,    1002(x31)
li                  x4,     0x80703784
pv.srl.sci.b        x23,    x4,     21
sw                  x23,    556(x31)
li                  x0,     0xcdf76944
pv.srl.sci.b        x23,    x0,     30
sw                  x23,    193(x31)
li                  x30,    0x2c9fc2f
li                  x26,    0xe5129526
pv.sra.h            x13,    x30,    x26
sw                  x13,    0(x31)
li                  x6,     0x6882a67e
li                  x6,     0x216ef32
pv.sra.h            x3,     x6,     x6
sw                  x3,     0(x31)
li                  x9,     0x6c14e6f6
li                  x17,    0xd9916289
pv.sra.h            x11,    x9,     x17
sw                  x11,    182(x31)
li                  x11,    0xacae94a3
li                  x11,    0x69cadd1f
pv.sra.b            x26,    x11,    x11
sw                  x26,    0(x31)
li                  x0,     0x5d7d8c88
li                  x26,    0x90eeebf0
pv.sra.b            x30,    x0,     x26
sw                  x30,    433(x31)
li                  x15,    0x161afb5a
li                  x28,    0xebb732fd
pv.sra.b            x29,    x15,    x28
sw                  x29,    275(x31)
li                  x20,    0xaebfa9ef
li                  x25,    0xbd6c0f06
pv.sra.sc.h         x9,     x20,    x25
sw                  x9,     0(x31)
li                  x27,    0xac519a0e
li                  x1,     0xee654986
pv.sra.sc.h         x13,    x27,    x1
sw                  x13,    1365(x31)
li                  x29,    0xdb1f623d
li                  x18,    0xd0c2d97a
pv.sra.sc.h         x28,    x29,    x18
sw                  x28,    0(x31)
li                  x2,     0xb292efc6
li                  x24,    0x79651614
pv.sra.sc.b         x28,    x2,     x24
sw                  x28,    0(x31)
li                  x0,     0x9b59ab03
li                  x20,    0x4d64b388
pv.sra.sc.b         x7,     x0,     x20
sw                  x7,     1812(x31)
li                  x12,    0x7b5768e8
li                  x13,    0x2ea48edc
pv.sra.sc.b         x9,     x12,    x13
sw                  x9,     0(x31)
li                  x26,    0x4639a2ef
pv.sra.sci.h        x9,     x26,    31
sw                  x9,     0(x31)
li                  x22,    0x6253dcd7
pv.sra.sci.h        x25,    x22,    8
sw                  x25,    0(x31)
li                  x22,    0xc0b8f5f4
pv.sra.sci.h        x6,     x22,    11
sw                  x6,     0(x31)
li                  x31,    0x9c789b78
pv.sra.sci.b        x30,    x31,    25
sw                  x30,    1844(x31)
li                  x21,    0x6c57ed29
pv.sra.sci.b        x29,    x21,    25
sw                  x29,    1657(x31)
li                  x28,    0xba2c25c8
pv.sra.sci.b        x13,    x28,    4
sw                  x13,    1484(x31)
li                  x26,    0x8e8cf949
li                  x1,     0xfa79fa64
pv.sll.h            x20,    x26,    x1
sw                  x20,    269(x31)
li                  x22,    0x289ba55
li                  x22,    0xf445d1d3
pv.sll.h            x19,    x22,    x22
sw                  x19,    684(x31)
li                  x28,    0xdd1150db
li                  x20,    0x57e7300c
pv.sll.h            x24,    x28,    x20
sw                  x24,    254(x31)
li                  x9,     0xd3cbe11
li                  x11,    0xd41e9c4a
pv.sll.b            x28,    x9,     x11
sw                  x28,    0(x31)
li                  x27,    0xc4e79ab2
li                  x2,     0x257f9fa
pv.sll.b            x18,    x27,    x2
sw                  x18,    0(x31)
li                  x28,    0x8eb088f1
li                  x8,     0x9691d549
pv.sll.b            x15,    x28,    x8
sw                  x15,    1214(x31)
li                  x30,    0xdb697cce
li                  x20,    0x533f7057
pv.sll.sc.h         x28,    x30,    x20
sw                  x28,    0(x31)
li                  x9,     0x596e2804
li                  x11,    0xb8271213
pv.sll.sc.h         x11,    x9,     x11
sw                  x11,    1591(x31)
li                  x14,    0x296210e9
li                  x8,     0xfb02aefc
pv.sll.sc.h         x25,    x14,    x8
sw                  x25,    117(x31)
li                  x11,    0x10dc6340
li                  x18,    0x8a645086
pv.sll.sc.b         x28,    x11,    x18
sw                  x28,    0(x31)
li                  x29,    0x5acd6b64
li                  x6,     0xe7579db0
pv.sll.sc.b         x1,     x29,    x6
sw                  x1,     311(x31)
li                  x27,    0xebddc80
li                  x5,     0x272a80df
pv.sll.sc.b         x12,    x27,    x5
sw                  x12,    352(x31)
li                  x17,    0x6644d161
pv.sll.sci.h        x1,     x17,    4
sw                  x1,     0(x31)
li                  x16,    0x21de6108
pv.sll.sci.h        x19,    x16,    20
sw                  x19,    0(x31)
li                  x13,    0x162db7d4
pv.sll.sci.h        x29,    x13,    6
sw                  x29,    0(x31)
li                  x27,    0x58c9ffc9
pv.sll.sci.b        x30,    x27,    27
sw                  x30,    998(x31)
li                  x8,     0x291c96e8
pv.sll.sci.b        x22,    x8,     18
sw                  x22,    0(x31)
li                  x30,    0x2c095978
pv.sll.sci.b        x25,    x30,    25
sw                  x25,    963(x31)
li                  x27,    0xa104904f
li                  x7,     0xff7da8d4
pv.or.h             x2,     x27,    x7
sw                  x2,     1574(x31)
li                  x29,    0xbc33502
li                  x26,    0xd7c4d3e
pv.or.h             x4,     x29,    x26
sw                  x4,     0(x31)
li                  x15,    0x5c5fa322
li                  x18,    0x98efeb42
pv.or.h             x21,    x15,    x18
sw                  x21,    0(x31)
li                  x1,     0xd8c15f5f
li                  x4,     0x89f1944e
pv.or.b             x2,     x1,     x4
sw                  x2,     0(x31)
li                  x12,    0xdebd87f2
li                  x14,    0x98dda085
pv.or.b             x17,    x12,    x14
sw                  x17,    0(x31)
li                  x22,    0x13e933d8
li                  x23,    0xaf0835f5
pv.or.b             x19,    x22,    x23
sw                  x19,    0(x31)
li                  x27,    0x2f82fa2b
li                  x24,    0x7c45f7bd
pv.or.sc.h          x22,    x27,    x24
sw                  x22,    0(x31)
li                  x20,    0xa3c8e24f
li                  x1,     0x9a90e3cf
pv.or.sc.h          x10,    x20,    x1
sw                  x10,    0(x31)
li                  x18,    0x59da307f
li                  x15,    0x39bc7890
pv.or.sc.h          x15,    x18,    x15
sw                  x15,    222(x31)
li                  x30,    0xb5e499d3
li                  x11,    0xc073fe7
pv.or.sc.b          x28,    x30,    x11
sw                  x28,    0(x31)
li                  x19,    0x535f14e9
li                  x21,    0xbcec0bc4
pv.or.sc.b          x20,    x19,    x21
sw                  x20,    0(x31)
li                  x15,    0x9693cdc5
li                  x31,    0x798e04b6
pv.or.sc.b          x20,    x15,    x31
sw                  x20,    1868(x31)
li                  x22,    0x9fe7c0e7
pv.or.sci.h         x10,    x22,    1
sw                  x10,    745(x31)
li                  x19,    0xe7bdb8c5
pv.or.sci.h         x7,     x19,    12
sw                  x7,     507(x31)
li                  x29,    0x3354cb0b
pv.or.sci.h         x28,    x29,    6
sw                  x28,    1330(x31)
li                  x0,     0xf9c54e03
pv.or.sci.b         x27,    x0,     2
sw                  x27,    1222(x31)
li                  x20,    0x81c3dd77
pv.or.sci.b         x24,    x20,    0
sw                  x24,    0(x31)
li                  x18,    0x6037c7f4
pv.or.sci.b         x4,     x18,    10
sw                  x4,     0(x31)
li                  x23,    0x2b89d128
li                  x27,    0x69a2c901
pv.xor.h            x1,     x23,    x27
sw                  x1,     1245(x31)
li                  x14,    0x944be93a
li                  x2,     0xe137344a
pv.xor.h            x22,    x14,    x2
sw                  x22,    0(x31)
li                  x14,    0xf426d9be
li                  x28,    0x808fe93b
pv.xor.h            x6,     x14,    x28
sw                  x6,     583(x31)
li                  x17,    0xac361bde
li                  x16,    0xb20fbb68
pv.xor.b            x9,     x17,    x16
sw                  x9,     0(x31)
li                  x24,    0x12a0e907
li                  x4,     0xef081937
pv.xor.b            x4,     x24,    x4
sw                  x4,     1303(x31)
li                  x6,     0x71a7443
li                  x28,    0xe894b78f
pv.xor.b            x4,     x6,     x28
sw                  x4,     1052(x31)
li                  x11,    0x80194481
li                  x9,     0x49266c76
pv.xor.sc.h         x22,    x11,    x9
sw                  x22,    0(x31)
li                  x27,    0xba08989e
li                  x30,    0x6be855a0
pv.xor.sc.h         x26,    x27,    x30
sw                  x26,    1888(x31)
li                  x25,    0x2b0d9dc3
li                  x5,     0x9cfb68c7
pv.xor.sc.h         x11,    x25,    x5
sw                  x11,    0(x31)
li                  x25,    0xd4bb2c0e
li                  x31,    0x47bb41f7
pv.xor.sc.b         x3,     x25,    x31
sw                  x3,     0(x31)
li                  x16,    0xaa742045
li                  x17,    0xb9d17e1b
pv.xor.sc.b         x8,     x16,    x17
sw                  x8,     0(x31)
li                  x23,    0x21d631e9
li                  x10,    0x1469cce3
pv.xor.sc.b         x4,     x23,    x10
sw                  x4,     1451(x31)
li                  x0,     0x82442842
pv.xor.sci.h        x12,    x0,     12
sw                  x12,    1288(x31)
li                  x23,    0xa2f46a80
pv.xor.sci.h        x10,    x23,    16
sw                  x10,    0(x31)
li                  x10,    0xbe5648d2
pv.xor.sci.h        x3,     x10,    27
sw                  x3,     1551(x31)
li                  x21,    0xbdcc5cc
pv.xor.sci.b        x20,    x21,    24
sw                  x20,    664(x31)
li                  x30,    0xece14b97
pv.xor.sci.b        x18,    x30,    11
sw                  x18,    948(x31)
li                  x31,    0x114e0b4c
pv.xor.sci.b        x6,     x31,    26
sw                  x6,     1165(x31)
li                  x2,     0xff225a4f
li                  x29,    0x73ef20b
pv.and.h            x28,    x2,     x29
sw                  x28,    0(x31)
li                  x23,    0x46459802
li                  x16,    0x5834dd8a
pv.and.h            x10,    x23,    x16
sw                  x10,    0(x31)
li                  x21,    0x6070223c
li                  x23,    0xc59e2168
pv.and.h            x26,    x21,    x23
sw                  x26,    0(x31)
li                  x4,     0x9148679c
li                  x25,    0x2ec9746d
pv.and.b            x11,    x4,     x25
sw                  x11,    0(x31)
li                  x28,    0x5ad4c5c8
li                  x30,    0x3431b5d1
pv.and.b            x6,     x28,    x30
sw                  x6,     0(x31)
li                  x2,     0x5f45c53
li                  x17,    0x5a5510d5
pv.and.b            x16,    x2,     x17
sw                  x16,    1854(x31)
li                  x6,     0x4f026189
li                  x23,    0xf762f7de
pv.and.sc.h         x26,    x6,     x23
sw                  x26,    1104(x31)
li                  x24,    0xb4eb7862
li                  x3,     0x6ffe88f
pv.and.sc.h         x1,     x24,    x3
sw                  x1,     1113(x31)
li                  x0,     0x18554773
li                  x28,    0xede9565c
pv.and.sc.h         x8,     x0,     x28
sw                  x8,     0(x31)
li                  x21,    0xfefe4d89
li                  x18,    0xb9e8836c
pv.and.sc.b         x1,     x21,    x18
sw                  x1,     0(x31)
li                  x25,    0x98848d63
li                  x10,    0x198c603
pv.and.sc.b         x19,    x25,    x10
sw                  x19,    0(x31)
li                  x11,    0xdf62f68c
li                  x9,     0x98fd2614
pv.and.sc.b         x18,    x11,    x9
sw                  x18,    0(x31)
li                  x14,    0x4d3ef162
pv.and.sci.h        x5,     x14,    18
sw                  x5,     2004(x31)
li                  x13,    0x58ee83f5
pv.and.sci.h        x13,    x13,    11
sw                  x13,    0(x31)
li                  x9,     0xa74385c2
pv.and.sci.h        x4,     x9,     22
sw                  x4,     0(x31)
li                  x13,    0xfaa0fd4e
pv.and.sci.b        x18,    x13,    7
sw                  x18,    0(x31)
li                  x16,    0xd3788724
pv.and.sci.b        x21,    x16,    26
sw                  x21,    620(x31)
li                  x4,     0x449833f
pv.and.sci.b        x29,    x4,     14
sw                  x29,    546(x31)
li                  x14,    0x81586f1e
li                  x18,    0xb4a19bff
pv.dotusp.h         x4,     x14,    x18
sw                  x4,     0(x31)
li                  x31,    0xde9bbfd4
li                  x15,    0x5093cfb0
pv.dotusp.h         x8,     x31,    x15
sw                  x8,     1283(x31)
li                  x28,    0xce296b06
li                  x2,     0x24d6b579
pv.dotusp.h         x13,    x28,    x2
sw                  x13,    185(x31)
li                  x28,    0xb0e8eff2
li                  x28,    0x9df46208
pv.dotusp.b         x28,    x28,    x28
sw                  x28,    0(x31)
li                  x13,    0x52313b87
li                  x5,     0xb6728881
pv.dotusp.b         x8,     x13,    x5
sw                  x8,     111(x31)
li                  x1,     0x1d89f409
li                  x5,     0x4d4dde4d
pv.dotusp.b         x22,    x1,     x5
sw                  x22,    1464(x31)
li                  x13,    0x69d5bc10
li                  x4,     0xea3f46a0
pv.dotusp.sc.h      x27,    x13,    x4
sw                  x27,    0(x31)
li                  x10,    0x31d2281d
li                  x15,    0x5cfa1365
pv.dotusp.sc.h      x28,    x10,    x15
sw                  x28,    0(x31)
li                  x3,     0xe960480a
li                  x16,    0x55d5f8ac
pv.dotusp.sc.h      x15,    x3,     x16
sw                  x15,    0(x31)
li                  x4,     0x2a325c9f
li                  x23,    0xab7772f7
pv.dotusp.sc.b      x30,    x4,     x23
sw                  x30,    1666(x31)
li                  x1,     0x6bb94b2f
li                  x15,    0x43ce18d6
pv.dotusp.sc.b      x26,    x1,     x15
sw                  x26,    1544(x31)
li                  x21,    0xc3729aa5
li                  x16,    0x71615582
pv.dotusp.sc.b      x29,    x21,    x16
sw                  x29,    0(x31)
li                  x18,    0x2342d7c
pv.dotusp.sci.h     x26,    x18,    29
sw                  x26,    1781(x31)
li                  x26,    0x9981cc06
pv.dotusp.sci.h     x14,    x26,    17
sw                  x14,    1908(x31)
li                  x24,    0x51f22487
pv.dotusp.sci.h     x27,    x24,    6
sw                  x27,    945(x31)
li                  x4,     0xc19c708c
pv.dotusp.sci.b     x19,    x4,     0
sw                  x19,    222(x31)
li                  x29,    0xd5d71cf
pv.dotusp.sci.b     x21,    x29,    4
sw                  x21,    0(x31)
li                  x26,    0x85f56dcc
pv.dotusp.sci.b     x13,    x26,    20
sw                  x13,    390(x31)
li                  x21,    0xc007fe10
li                  x9,     0x286ca75a
pv.dotsp.h          x25,    x21,    x9
sw                  x25,    0(x31)
li                  x29,    0x2eebe487
li                  x22,    0xdd971ea
pv.dotsp.h          x28,    x29,    x22
sw                  x28,    480(x31)
li                  x8,     0xef9dec9b
li                  x24,    0x5a48fedf
pv.dotsp.h          x9,     x8,     x24
sw                  x9,     1090(x31)
li                  x10,    0xd7fb94bd
li                  x15,    0xdaf3a8cd
pv.dotsp.b          x22,    x10,    x15
sw                  x22,    812(x31)
li                  x4,     0xa3997262
li                  x22,    0xe3940956
pv.dotsp.b          x9,     x4,     x22
sw                  x9,     0(x31)
li                  x11,    0x48ae9c69
li                  x25,    0x1a5672a9
pv.dotsp.b          x19,    x11,    x25
sw                  x19,    1392(x31)
li                  x19,    0x3d8598da
li                  x6,     0x751e146b
pv.dotsp.sc.h       x21,    x19,    x6
sw                  x21,    0(x31)
li                  x10,    0x66c5d297
li                  x14,    0x9bcb30cc
pv.dotsp.sc.h       x3,     x10,    x14
sw                  x3,     380(x31)
li                  x3,     0xba2dd382
li                  x0,     0xdd89c5fe
pv.dotsp.sc.h       x25,    x3,     x0
sw                  x25,    0(x31)
li                  x10,    0xd6e098b1
li                  x18,    0x3d6fe320
pv.dotsp.sc.b       x11,    x10,    x18
sw                  x11,    643(x31)
li                  x20,    0x154b7e77
li                  x8,     0xfcfd522
pv.dotsp.sc.b       x1,     x20,    x8
sw                  x1,     382(x31)
li                  x7,     0xe581507f
li                  x26,    0x9c92322c
pv.dotsp.sc.b       x13,    x7,     x26
sw                  x13,    852(x31)
li                  x23,    0xdfbc35
pv.dotsp.sci.h      x5,     x23,    21
sw                  x5,     0(x31)
li                  x1,     0x16f2f4d2
pv.dotsp.sci.h      x16,    x1,     28
sw                  x16,    0(x31)
li                  x10,    0x59df6aa6
pv.dotsp.sci.h      x20,    x10,    26
sw                  x20,    842(x31)
li                  x15,    0x8f8306ce
pv.dotsp.sci.b      x20,    x15,    2
sw                  x20,    1331(x31)
li                  x3,     0x16f08976
pv.dotsp.sci.b      x22,    x3,     31
sw                  x22,    0(x31)
li                  x14,    0xed4b748a
pv.dotsp.sci.b      x11,    x14,    24
sw                  x11,    186(x31)
li                  x6,     0x5a5e2abc
li                  x9,     0xee61958a
pv.sdotup.h         x16,    x6,     x9
sw                  x16,    17(x31)
li                  x15,    0xc8e1e205
li                  x7,     0x309ecd58
pv.sdotup.h         x3,     x15,    x7
sw                  x3,     0(x31)
li                  x7,     0xaa6758a9
li                  x28,    0xedeaeb1c
pv.sdotup.h         x13,    x7,     x28
sw                  x13,    0(x31)
li                  x12,    0x79249a50
li                  x19,    0x93f1dea4
pv.sdotup.b         x23,    x12,    x19
sw                  x23,    0(x31)
li                  x12,    0xf43ae33e
li                  x29,    0x638752d
pv.sdotup.b         x13,    x12,    x29
sw                  x13,    0(x31)
li                  x14,    0x49d712ca
li                  x15,    0x5172029e
pv.sdotup.b         x8,     x14,    x15
sw                  x8,     0(x31)
li                  x4,     0x9d02017e
li                  x31,    0xdc56aa71
pv.sdotup.sc.h      x6,     x4,     x31
sw                  x6,     1040(x31)
li                  x31,    0x737edb81
li                  x23,    0x4f40add2
pv.sdotup.sc.h      x11,    x31,    x23
sw                  x11,    776(x31)
li                  x13,    0xb800f5d7
li                  x0,     0xdef18dcd
pv.sdotup.sc.h      x19,    x13,    x0
sw                  x19,    150(x31)
li                  x18,    0x7466464a
li                  x11,    0xac2535a
pv.sdotup.sc.b      x8,     x18,    x11
sw                  x8,     865(x31)
li                  x2,     0x54bf550e
li                  x28,    0xd12239c
pv.sdotup.sc.b      x12,    x2,     x28
sw                  x12,    177(x31)
li                  x18,    0x11edb884
li                  x25,    0xdc2eb69c
pv.sdotup.sc.b      x26,    x18,    x25
sw                  x26,    0(x31)
li                  x22,    0xea38d20e
pv.sdotup.sci.h     x20,    x22,    1
sw                  x20,    0(x31)
li                  x22,    0x5387bf5d
pv.sdotup.sci.h     x9,     x22,    4
sw                  x9,     951(x31)
li                  x29,    0x32990bfc
pv.sdotup.sci.h     x20,    x29,    1
sw                  x20,    0(x31)
li                  x18,    0x1ff8fc81
pv.sdotup.sci.b     x1,     x18,    23
sw                  x1,     943(x31)
li                  x9,     0xddd7bf1c
pv.sdotup.sci.b     x2,     x9,     21
sw                  x2,     0(x31)
li                  x9,     0xdc5902c7
pv.sdotup.sci.b     x1,     x9,     2
sw                  x1,     0(x31)
li                  x23,    0x9f8dae3c
li                  x10,    0xa1b5bcb0
pv.sdotusp.h        x28,    x23,    x10
sw                  x28,    425(x31)
li                  x18,    0x26dab48b
li                  x17,    0xa3a4482f
pv.sdotusp.h        x29,    x18,    x17
sw                  x29,    0(x31)
li                  x5,     0xfd6ce51f
li                  x18,    0x7719610a
pv.sdotusp.h        x28,    x5,     x18
sw                  x28,    1245(x31)
li                  x29,    0x3c6021b2
li                  x7,     0x2995115e
pv.sdotusp.b        x4,     x29,    x7
sw                  x4,     324(x31)
li                  x21,    0x47ed9014
li                  x6,     0xd64b4e8a
pv.sdotusp.b        x2,     x21,    x6
sw                  x2,     1591(x31)
li                  x25,    0x64ce277a
li                  x16,    0x83cb930c
pv.sdotusp.b        x5,     x25,    x16
sw                  x5,     0(x31)
li                  x18,    0x6e09ff60
li                  x23,    0xc4627160
pv.sdotusp.sc.h     x9,     x18,    x23
sw                  x9,     0(x31)
li                  x1,     0xfbd567d9
li                  x27,    0xdf047d57
pv.sdotusp.sc.h     x4,     x1,     x27
sw                  x4,     1460(x31)
li                  x16,    0x7335cd2a
li                  x9,     0xbbd8be1e
pv.sdotusp.sc.h     x9,     x16,    x9
sw                  x9,     0(x31)
li                  x3,     0x2c76e041
li                  x1,     0x75e465c7
pv.sdotusp.sc.b     x7,     x3,     x1
sw                  x7,     1407(x31)
li                  x31,    0x47a14068
li                  x6,     0xe879fccc
pv.sdotusp.sc.b     x10,    x31,    x6
sw                  x10,    0(x31)
li                  x25,    0x83f18cc8
li                  x4,     0xf1672589
pv.sdotusp.sc.b     x30,    x25,    x4
sw                  x30,    0(x31)
li                  x7,     0x8c078c94
pv.sdotusp.sci.h    x16,    x7,     18
sw                  x16,    0(x31)
li                  x27,    0xa01787a7
pv.sdotusp.sci.h    x27,    x27,    12
sw                  x27,    1442(x31)
li                  x4,     0xa2a85800
pv.sdotusp.sci.h    x27,    x4,     4
sw                  x27,    0(x31)
li                  x15,    0xf7e6b1ca
pv.sdotusp.sci.b    x24,    x15,    1
sw                  x24,    1031(x31)
li                  x4,     0x75a34312
pv.sdotusp.sci.b    x6,     x4,     0
sw                  x6,     746(x31)
li                  x7,     0xc9d6595b
pv.sdotusp.sci.b    x30,    x7,     29
sw                  x30,    1149(x31)
li                  x31,    0x8c7846dd
li                  x23,    0x44904efc
pv.sdotsp.h         x7,     x31,    x23
sw                  x7,     1870(x31)
li                  x21,    0x5da8659a
li                  x1,     0xee3b3dfe
pv.sdotsp.h         x9,     x21,    x1
sw                  x9,     240(x31)
li                  x10,    0x3344a461
li                  x31,    0x6d8bb564
pv.sdotsp.h         x21,    x10,    x31
sw                  x21,    1742(x31)
li                  x12,    0x4568c46d
li                  x27,    0x2096abed
pv.sdotsp.b         x19,    x12,    x27
sw                  x19,    0(x31)
li                  x14,    0xb385c662
li                  x30,    0xbb747ce1
pv.sdotsp.b         x10,    x14,    x30
sw                  x10,    0(x31)
li                  x22,    0x60db38f1
li                  x16,    0x608da33a
pv.sdotsp.b         x17,    x22,    x16
sw                  x17,    700(x31)
li                  x2,     0xb9defae
li                  x25,    0x867c77eb
pv.sdotsp.sc.h      x17,    x2,     x25
sw                  x17,    0(x31)
li                  x23,    0x24792234
li                  x3,     0x8e60e842
pv.sdotsp.sc.h      x25,    x23,    x3
sw                  x25,    1444(x31)
li                  x1,     0xb67ad77e
li                  x24,    0xe4903ac0
pv.sdotsp.sc.h      x25,    x1,     x24
sw                  x25,    1193(x31)
li                  x3,     0x9ef1201c
li                  x24,    0x86c71b6
pv.sdotsp.sc.b      x11,    x3,     x24
sw                  x11,    0(x31)
li                  x2,     0xa465fa1f
li                  x0,     0x76195072
pv.sdotsp.sc.b      x13,    x2,     x0
sw                  x13,    196(x31)
li                  x9,     0xe5c3dd11
li                  x29,    0x20be958e
pv.sdotsp.sc.b      x4,     x9,     x29
sw                  x4,     189(x31)
li                  x1,     0x86758aaa
pv.sdotsp.sci.h     x5,     x1,     13
sw                  x5,     0(x31)
li                  x14,    0xf75d9076
pv.sdotsp.sci.h     x18,    x14,    19
sw                  x18,    1313(x31)
li                  x1,     0x4f9d1b5b
pv.sdotsp.sci.h     x2,     x1,     29
sw                  x2,     0(x31)
li                  x8,     0xcd2ac975
pv.sdotsp.sci.b     x28,    x8,     16
sw                  x28,    0(x31)
li                  x8,     0xe182bce
pv.sdotsp.sci.b     x21,    x8,     21
sw                  x21,    264(x31)
li                  x29,    0x66b258c3
pv.sdotsp.sci.b     x26,    x29,    14
sw                  x26,    0(x31)
li                  x28,    0x80d1314f
li                  x6,     0xcaff1d66
pv.cmpeq.h          x8,     x28,    x6
sw                  x8,     1710(x31)
li                  x21,    0xda82e840
li                  x24,    0x813278c1
pv.cmpeq.h          x25,    x21,    x24
sw                  x25,    0(x31)
li                  x3,     0x1234213b
li                  x14,    0x8c688dcd
pv.cmpeq.h          x16,    x3,     x14
sw                  x16,    581(x31)
li                  x18,    0x6c0e076b
li                  x15,    0x15eed5e9
pv.cmpeq.b          x28,    x18,    x15
sw                  x28,    0(x31)
li                  x24,    0x4774609e
li                  x23,    0x72bc6aa
pv.cmpeq.b          x9,     x24,    x23
sw                  x9,     0(x31)
li                  x28,    0xc1da988b
li                  x14,    0x564dea17
pv.cmpeq.b          x12,    x28,    x14
sw                  x12,    2036(x31)
li                  x4,     0xa880c244
li                  x20,    0x6c5151a1
pv.cmpeq.sc.h       x18,    x4,     x20
sw                  x18,    1437(x31)
li                  x11,    0x3348ffa1
li                  x8,     0xb9d9fe68
pv.cmpeq.sc.h       x21,    x11,    x8
sw                  x21,    0(x31)
li                  x7,     0xc1ef9600
li                  x18,    0xf0adf662
pv.cmpeq.sc.h       x29,    x7,     x18
sw                  x29,    1025(x31)
li                  x6,     0x2144faa9
li                  x16,    0xa7940fa1
pv.cmpeq.sc.b       x27,    x6,     x16
sw                  x27,    1611(x31)
li                  x25,    0x85622765
li                  x23,    0x5d0d0f7
pv.cmpeq.sc.b       x9,     x25,    x23
sw                  x9,     0(x31)
li                  x2,     0x4df7e934
li                  x2,     0xd90b2c0
pv.cmpeq.sc.b       x21,    x2,     x2
sw                  x21,    901(x31)
li                  x15,    0xb1a6a3dc
pv.cmpeq.sci.h      x30,    x15,    18
sw                  x30,    0(x31)
li                  x20,    0xaf7df3b2
pv.cmpeq.sci.h      x21,    x20,    31
sw                  x21,    0(x31)
li                  x10,    0xc77522c
pv.cmpeq.sci.h      x26,    x10,    15
sw                  x26,    832(x31)
li                  x25,    0x6d56e3ce
pv.cmpeq.sci.b      x5,     x25,    1
sw                  x5,     1596(x31)
li                  x6,     0xe5eedb9d
pv.cmpeq.sci.b      x25,    x6,     28
sw                  x25,    527(x31)
li                  x10,    0x4ac91cb9
pv.cmpeq.sci.b      x4,     x10,    23
sw                  x4,     0(x31)
li                  x10,    0xfbec2595
li                  x10,    0xa8e7fdc9
pv.cmpne.h          x23,    x10,    x10
sw                  x23,    0(x31)
li                  x26,    0x6679a312
li                  x21,    0x2cb0e1f6
pv.cmpne.h          x12,    x26,    x21
sw                  x12,    406(x31)
li                  x21,    0x5cf8586c
li                  x11,    0xe0ecf0b
pv.cmpne.h          x8,     x21,    x11
sw                  x8,     660(x31)
li                  x12,    0xd74eebb5
li                  x5,     0x2de6e2f0
pv.cmpne.b          x29,    x12,    x5
sw                  x29,    0(x31)
li                  x7,     0x44692ecd
li                  x15,    0x33ff9674
pv.cmpne.b          x3,     x7,     x15
sw                  x3,     0(x31)
li                  x8,     0x6ca36420
li                  x31,    0x5cdc6e88
pv.cmpne.b          x27,    x8,     x31
sw                  x27,    0(x31)
li                  x23,    0x7f9f97f9
li                  x4,     0x8fa5cfee
pv.cmpne.sc.h       x28,    x23,    x4
sw                  x28,    1054(x31)
li                  x29,    0xa9f794f1
li                  x20,    0x19f192b6
pv.cmpne.sc.h       x25,    x29,    x20
sw                  x25,    1428(x31)
li                  x2,     0x78398fba
li                  x21,    0xf28312d1
pv.cmpne.sc.h       x24,    x2,     x21
sw                  x24,    0(x31)
li                  x25,    0x82cf561f
li                  x14,    0xde6d0ae7
pv.cmpne.sc.b       x21,    x25,    x14
sw                  x21,    0(x31)
li                  x29,    0xd0ae2b18
li                  x24,    0xb7cc2384
pv.cmpne.sc.b       x18,    x29,    x24
sw                  x18,    0(x31)
li                  x19,    0x66bf56a6
li                  x12,    0x2701eba
pv.cmpne.sc.b       x18,    x19,    x12
sw                  x18,    0(x31)
li                  x28,    0x82d8633d
pv.cmpne.sci.h      x10,    x28,    1
sw                  x10,    1575(x31)
li                  x21,    0xaee68304
pv.cmpne.sci.h      x3,     x21,    15
sw                  x3,     1956(x31)
li                  x18,    0xe0d2c009
pv.cmpne.sci.h      x5,     x18,    9
sw                  x5,     932(x31)
li                  x3,     0x3c53d55c
pv.cmpne.sci.b      x27,    x3,     3
sw                  x27,    1619(x31)
li                  x19,    0xdc5c6e55
pv.cmpne.sci.b      x20,    x19,    7
sw                  x20,    1039(x31)
li                  x8,     0x36e7c00f
pv.cmpne.sci.b      x17,    x8,     10
sw                  x17,    0(x31)
li                  x25,    0xad48f1e5
li                  x24,    0xda636f35
pv.cmpgt.h          x29,    x25,    x24
sw                  x29,    1940(x31)
li                  x26,    0x5a9cb5ae
li                  x23,    0xc31c0eb9
pv.cmpgt.h          x5,     x26,    x23
sw                  x5,     1570(x31)
li                  x28,    0x629da335
li                  x15,    0x5ea2e610
pv.cmpgt.h          x8,     x28,    x15
sw                  x8,     1153(x31)
li                  x2,     0x36dc1e4d
li                  x14,    0xdcfaffaa
pv.cmpgt.b          x1,     x2,     x14
sw                  x1,     1626(x31)
li                  x1,     0x36a952a4
li                  x18,    0x60c88d9e
pv.cmpgt.b          x29,    x1,     x18
sw                  x29,    1336(x31)
li                  x29,    0xf27fdd80
li                  x30,    0xab5660ed
pv.cmpgt.b          x30,    x29,    x30
sw                  x30,    634(x31)
li                  x3,     0x195ea8ca
li                  x1,     0x71cf5ed5
pv.cmpgt.sc.h       x17,    x3,     x1
sw                  x17,    675(x31)
li                  x8,     0xee85e8ca
li                  x14,    0x6a4bd5cb
pv.cmpgt.sc.h       x1,     x8,     x14
sw                  x1,     1207(x31)
li                  x17,    0x2b354144
li                  x23,    0xf23f2cf3
pv.cmpgt.sc.h       x23,    x17,    x23
sw                  x23,    696(x31)
li                  x28,    0xa2730266
li                  x4,     0x1c2b44a6
pv.cmpgt.sc.b       x9,     x28,    x4
sw                  x9,     679(x31)
li                  x6,     0x2015e528
li                  x29,    0x8bf89605
pv.cmpgt.sc.b       x15,    x6,     x29
sw                  x15,    0(x31)
li                  x8,     0x57ce1136
li                  x13,    0x52aa5578
pv.cmpgt.sc.b       x21,    x8,     x13
sw                  x21,    0(x31)
li                  x2,     0x98cb901e
pv.cmpgt.sci.h      x6,     x2,     13
sw                  x6,     540(x31)
li                  x19,    0x19933339
pv.cmpgt.sci.h      x18,    x19,    28
sw                  x18,    300(x31)
li                  x18,    0xb4582a44
pv.cmpgt.sci.h      x5,     x18,    31
sw                  x5,     0(x31)
li                  x10,    0x61353e99
pv.cmpgt.sci.b      x22,    x10,    2
sw                  x22,    232(x31)
li                  x1,     0x7ec2b68a
pv.cmpgt.sci.b      x16,    x1,     22
sw                  x16,    0(x31)
li                  x24,    0x4ee02367
pv.cmpgt.sci.b      x12,    x24,    1
sw                  x12,    1572(x31)
li                  x19,    0xd6aa2cd4
li                  x22,    0x5dadbe5a
pv.cmpge.h          x7,     x19,    x22
sw                  x7,     1050(x31)
li                  x25,    0xf4f068d3
li                  x13,    0x48ec896
pv.cmpge.h          x23,    x25,    x13
sw                  x23,    0(x31)
li                  x26,    0xfe1b440c
li                  x18,    0xf29e8c72
pv.cmpge.h          x3,     x26,    x18
sw                  x3,     1533(x31)
li                  x2,     0xddb34bb5
li                  x28,    0xd6f47139
pv.cmpge.b          x9,     x2,     x28
sw                  x9,     0(x31)
li                  x2,     0xef8a32bf
li                  x27,    0x276755e5
pv.cmpge.b          x26,    x2,     x27
sw                  x26,    0(x31)
li                  x0,     0x23963032
li                  x7,     0xbda9faac
pv.cmpge.b          x19,    x0,     x7
sw                  x19,    1010(x31)
li                  x30,    0x73aad68c
li                  x31,    0x1f97781b
pv.cmpge.sc.h       x6,     x30,    x31
sw                  x6,     1292(x31)
li                  x3,     0x2c7d736e
li                  x28,    0xe5372c90
pv.cmpge.sc.h       x28,    x3,     x28
sw                  x28,    882(x31)
li                  x1,     0x123fe3ea
li                  x13,    0xa4029f33
pv.cmpge.sc.h       x15,    x1,     x13
sw                  x15,    285(x31)
li                  x7,     0xee96b0d2
li                  x7,     0x5b9404fa
pv.cmpge.sc.b       x19,    x7,     x7
sw                  x19,    288(x31)
li                  x7,     0x42f8ad9
li                  x9,     0x7e3e18f6
pv.cmpge.sc.b       x13,    x7,     x9
sw                  x13,    409(x31)
li                  x4,     0xad8c45c6
li                  x9,     0xdf3b839e
pv.cmpge.sc.b       x13,    x4,     x9
sw                  x13,    549(x31)
li                  x11,    0x6d353882
pv.cmpge.sci.h      x28,    x11,    28
sw                  x28,    0(x31)
li                  x15,    0x244a933f
pv.cmpge.sci.h      x28,    x15,    17
sw                  x28,    0(x31)
li                  x16,    0x5c7a63d5
pv.cmpge.sci.h      x1,     x16,    21
sw                  x1,     1642(x31)
li                  x17,    0x1f2ef67
pv.cmpge.sci.b      x25,    x17,    5
sw                  x25,    1654(x31)
li                  x23,    0x8f0dc748
pv.cmpge.sci.b      x3,     x23,    6
sw                  x3,     0(x31)
li                  x7,     0xbcbc353d
pv.cmpge.sci.b      x22,    x7,     26
sw                  x22,    0(x31)
li                  x7,     0xf594912
li                  x9,     0x5a0928bb
pv.cmplt.h          x30,    x7,     x9
sw                  x30,    0(x31)
li                  x25,    0xd575c58b
li                  x25,    0x57eb3cf4
pv.cmplt.h          x18,    x25,    x25
sw                  x18,    0(x31)
li                  x19,    0x45dc7f9a
li                  x29,    0xff997ffc
pv.cmplt.h          x1,     x19,    x29
sw                  x1,     0(x31)
li                  x21,    0x798446e3
li                  x9,     0x95c051c4
pv.cmplt.b          x24,    x21,    x9
sw                  x24,    16(x31)
li                  x22,    0x9c12acfd
li                  x12,    0x94eb2e73
pv.cmplt.b          x20,    x22,    x12
sw                  x20,    0(x31)
li                  x12,    0x9efd46d6
li                  x26,    0x2385ba12
pv.cmplt.b          x13,    x12,    x26
sw                  x13,    0(x31)
li                  x20,    0x95188cd3
li                  x17,    0xc4bfa706
pv.cmplt.sc.h       x4,     x20,    x17
sw                  x4,     0(x31)
li                  x27,    0x92494b2
li                  x8,     0x584e44cf
pv.cmplt.sc.h       x23,    x27,    x8
sw                  x23,    0(x31)
li                  x0,     0x7a011bbc
li                  x17,    0x75d5cb86
pv.cmplt.sc.h       x27,    x0,     x17
sw                  x27,    0(x31)
li                  x1,     0x4d3fa966
li                  x0,     0xf4416510
pv.cmplt.sc.b       x19,    x1,     x0
sw                  x19,    294(x31)
li                  x0,     0x10605d48
li                  x12,    0xf2798a08
pv.cmplt.sc.b       x23,    x0,     x12
sw                  x23,    1654(x31)
li                  x20,    0x3a14435e
li                  x24,    0x37f42d67
pv.cmplt.sc.b       x23,    x20,    x24
sw                  x23,    0(x31)
li                  x9,     0x4703f2c8
pv.cmplt.sci.h      x17,    x9,     12
sw                  x17,    0(x31)
li                  x15,    0xa2cfbbfd
pv.cmplt.sci.h      x19,    x15,    31
sw                  x19,    0(x31)
li                  x22,    0xfa5accd
pv.cmplt.sci.h      x4,     x22,    3
sw                  x4,     1899(x31)
li                  x20,    0xe7859f78
pv.cmplt.sci.b      x10,    x20,    28
sw                  x10,    0(x31)
li                  x0,     0xf6193c03
pv.cmplt.sci.b      x18,    x0,     0
sw                  x18,    924(x31)
li                  x25,    0xdbae8cda
pv.cmplt.sci.b      x9,     x25,    2
sw                  x9,     0(x31)
li                  x13,    0x2b9aa9ee
li                  x5,     0x6270b0b4
pv.cmple.h          x24,    x13,    x5
sw                  x24,    1766(x31)
li                  x19,    0x13a98783
li                  x24,    0x72e6d77a
pv.cmple.h          x23,    x19,    x24
sw                  x23,    1458(x31)
li                  x15,    0x17dd3428
li                  x0,     0x94908cdf
pv.cmple.h          x13,    x15,    x0
sw                  x13,    619(x31)
li                  x24,    0x50859289
li                  x26,    0x903b8ed0
pv.cmple.b          x19,    x24,    x26
sw                  x19,    0(x31)
li                  x2,     0x6ece0629
li                  x9,     0x8fcaea88
pv.cmple.b          x17,    x2,     x9
sw                  x17,    610(x31)
li                  x11,    0x6b8807a5
li                  x20,    0x6bc2f4a0
pv.cmple.b          x19,    x11,    x20
sw                  x19,    0(x31)
li                  x30,    0x98db1d00
li                  x15,    0x6077d125
pv.cmple.sc.h       x23,    x30,    x15
sw                  x23,    603(x31)
li                  x4,     0x5fca4633
li                  x6,     0x55fc5fd
pv.cmple.sc.h       x21,    x4,     x6
sw                  x21,    0(x31)
li                  x31,    0xdd23a7cb
li                  x9,     0x202b6ba6
pv.cmple.sc.h       x29,    x31,    x9
sw                  x29,    341(x31)
li                  x19,    0xb6f0a240
li                  x11,    0x44fec9da
pv.cmple.sc.b       x19,    x19,    x11
sw                  x19,    1542(x31)
li                  x9,     0x94d01c6d
li                  x28,    0x22835cdc
pv.cmple.sc.b       x25,    x9,     x28
sw                  x25,    837(x31)
li                  x14,    0xc9985431
li                  x2,     0xa9d12c24
pv.cmple.sc.b       x24,    x14,    x2
sw                  x24,    497(x31)
li                  x14,    0x2df78b69
pv.cmple.sci.h      x4,     x14,    24
sw                  x4,     806(x31)
li                  x4,     0xad5a4e71
pv.cmple.sci.h      x27,    x4,     30
sw                  x27,    351(x31)
li                  x21,    0xea81544c
pv.cmple.sci.h      x18,    x21,    7
sw                  x18,    0(x31)
li                  x6,     0xe519d743
pv.cmple.sci.b      x6,     x6,     0
sw                  x6,     0(x31)
li                  x1,     0x55cdb2d0
pv.cmple.sci.b      x21,    x1,     6
sw                  x21,    237(x31)
li                  x22,    0xb2564a7d
pv.cmple.sci.b      x30,    x22,    17
sw                  x30,    0(x31)
li                  x15,    0xf84895d5
li                  x19,    0x1aaac502
pv.cmpgtu.h         x11,    x15,    x19
sw                  x11,    852(x31)
li                  x17,    0x75065d33
li                  x19,    0xc7a1af91
pv.cmpgtu.h         x11,    x17,    x19
sw                  x11,    0(x31)
li                  x23,    0x850ac2f2
li                  x10,    0xa8ca2a2c
pv.cmpgtu.h         x16,    x23,    x10
sw                  x16,    0(x31)
li                  x5,     0x633d063b
li                  x5,     0x103494e6
pv.cmpgtu.b         x30,    x5,     x5
sw                  x30,    0(x31)
li                  x31,    0xd668c59d
li                  x20,    0x8e3e2c2d
pv.cmpgtu.b         x29,    x31,    x20
sw                  x29,    0(x31)
li                  x14,    0xa41542ed
li                  x10,    0x972b134d
pv.cmpgtu.b         x11,    x14,    x10
sw                  x11,    0(x31)
li                  x2,     0xcf5009db
li                  x5,     0x906f4ea7
pv.cmpgtu.sc.h      x29,    x2,     x5
sw                  x29,    0(x31)
li                  x19,    0x4fafac00
li                  x18,    0xbb2e53b2
pv.cmpgtu.sc.h      x16,    x19,    x18
sw                  x16,    375(x31)
li                  x9,     0x213193f4
li                  x12,    0x44e9a09e
pv.cmpgtu.sc.h      x6,     x9,     x12
sw                  x6,     0(x31)
li                  x26,    0xa367ffe8
li                  x11,    0xa2151884
pv.cmpgtu.sc.b      x22,    x26,    x11
sw                  x22,    0(x31)
li                  x6,     0x148338e1
li                  x1,     0xdab2f949
pv.cmpgtu.sc.b      x18,    x6,     x1
sw                  x18,    0(x31)
li                  x25,    0x63f6d4a5
li                  x31,    0x9f37aa39
pv.cmpgtu.sc.b      x25,    x25,    x31
sw                  x25,    1698(x31)
li                  x14,    0x91a4211
pv.cmpgtu.sci.h     x29,    x14,    30
sw                  x29,    0(x31)
li                  x6,     0x162e4537
pv.cmpgtu.sci.h     x18,    x6,     29
sw                  x18,    0(x31)
li                  x10,    0xc718f4ff
pv.cmpgtu.sci.h     x24,    x10,    10
sw                  x24,    0(x31)
li                  x22,    0x4a95731
pv.cmpgtu.sci.b     x24,    x22,    30
sw                  x24,    0(x31)
li                  x18,    0xa9e67a0c
pv.cmpgtu.sci.b     x14,    x18,    6
sw                  x14,    0(x31)
li                  x2,     0xcbceec93
pv.cmpgtu.sci.b     x21,    x2,     4
sw                  x21,    0(x31)
li                  x10,    0xc9441aec
li                  x19,    0x12f70bad
pv.cmpgeu.h         x3,     x10,    x19
sw                  x3,     1320(x31)
li                  x8,     0x8bce3e9e
li                  x5,     0xee24ffa8
pv.cmpgeu.h         x7,     x8,     x5
sw                  x7,     1870(x31)
li                  x9,     0x4ddfccaa
li                  x9,     0x1fdcb3fa
pv.cmpgeu.h         x6,     x9,     x9
sw                  x6,     1061(x31)
li                  x24,    0x7f38df0c
li                  x0,     0xbb83851a
pv.cmpgeu.b         x14,    x24,    x0
sw                  x14,    0(x31)
li                  x12,    0xcd4b530c
li                  x8,     0x154f2f8b
pv.cmpgeu.b         x2,     x12,    x8
sw                  x2,     0(x31)
li                  x0,     0xf1ba021a
li                  x14,    0x21c73d67
pv.cmpgeu.b         x22,    x0,     x14
sw                  x22,    0(x31)
li                  x24,    0xbfe962af
li                  x9,     0xe78b57
pv.cmpgeu.sc.h      x10,    x24,    x9
sw                  x10,    0(x31)
li                  x7,     0x2014a3b6
li                  x16,    0xd4d1fc22
pv.cmpgeu.sc.h      x13,    x7,     x16
sw                  x13,    0(x31)
li                  x20,    0xf1b59f94
li                  x0,     0x222e3d65
pv.cmpgeu.sc.h      x20,    x20,    x0
sw                  x20,    204(x31)
li                  x20,    0xcb9c1bfb
li                  x25,    0x411db976
pv.cmpgeu.sc.b      x29,    x20,    x25
sw                  x29,    0(x31)
li                  x22,    0x2d1dc88
li                  x3,     0x9db2d2dd
pv.cmpgeu.sc.b      x11,    x22,    x3
sw                  x11,    1466(x31)
li                  x25,    0x2270527c
li                  x18,    0x1adaaa59
pv.cmpgeu.sc.b      x17,    x25,    x18
sw                  x17,    0(x31)
li                  x2,     0xa93f4638
pv.cmpgeu.sci.h     x16,    x2,     24
sw                  x16,    592(x31)
li                  x15,    0xc7e6a957
pv.cmpgeu.sci.h     x7,     x15,    11
sw                  x7,     607(x31)
li                  x23,    0x3133ad54
pv.cmpgeu.sci.h     x30,    x23,    24
sw                  x30,    0(x31)
li                  x15,    0x2964da1e
pv.cmpgeu.sci.b     x17,    x15,    8
sw                  x17,    0(x31)
li                  x2,     0xf267173b
pv.cmpgeu.sci.b     x30,    x2,     29
sw                  x30,    1455(x31)
li                  x10,    0x8488972a
pv.cmpgeu.sci.b     x3,     x10,    30
sw                  x3,     1521(x31)
li                  x2,     0xb59ffb8a
li                  x2,     0xda8b723d
pv.cmpltu.h         x22,    x2,     x2
sw                  x22,    51(x31)
li                  x10,    0x1fb812e6
li                  x8,     0x92ebe0fd
pv.cmpltu.h         x8,     x10,    x8
sw                  x8,     1337(x31)
li                  x10,    0x731c221f
li                  x21,    0xf8f93b8b
pv.cmpltu.h         x24,    x10,    x21
sw                  x24,    0(x31)
li                  x20,    0x541a999d
li                  x2,     0xbd6a960
pv.cmpltu.b         x3,     x20,    x2
sw                  x3,     0(x31)
li                  x2,     0x1ba7168b
li                  x19,    0x179dcc61
pv.cmpltu.b         x19,    x2,     x19
sw                  x19,    534(x31)
li                  x28,    0xf6dc54d3
li                  x18,    0xf299200
pv.cmpltu.b         x30,    x28,    x18
sw                  x30,    1747(x31)
li                  x31,    0xf265ec57
li                  x14,    0xee8c1eb3
pv.cmpltu.sc.h      x30,    x31,    x14
sw                  x30,    0(x31)
li                  x16,    0x357462f7
li                  x29,    0xd831080e
pv.cmpltu.sc.h      x24,    x16,    x29
sw                  x24,    0(x31)
li                  x3,     0x969fd569
li                  x22,    0x2f15107b
pv.cmpltu.sc.h      x26,    x3,     x22
sw                  x26,    1143(x31)
li                  x31,    0x32f69b50
li                  x16,    0xc28807e2
pv.cmpltu.sc.b      x15,    x31,    x16
sw                  x15,    0(x31)
li                  x25,    0xe21e15ab
li                  x4,     0x778ebe69
pv.cmpltu.sc.b      x17,    x25,    x4
sw                  x17,    1610(x31)
li                  x7,     0xba796a94
li                  x28,    0x1548d3d8
pv.cmpltu.sc.b      x18,    x7,     x28
sw                  x18,    0(x31)
li                  x6,     0x6a3f0fcd
pv.cmpltu.sci.h     x8,     x6,     24
sw                  x8,     0(x31)
li                  x8,     0x5d70e638
pv.cmpltu.sci.h     x12,    x8,     16
sw                  x12,    0(x31)
li                  x24,    0xbfe460af
pv.cmpltu.sci.h     x18,    x24,    13
sw                  x18,    199(x31)
li                  x29,    0xb22aba9d
pv.cmpltu.sci.b     x21,    x29,    6
sw                  x21,    0(x31)
li                  x29,    0xf4138734
pv.cmpltu.sci.b     x12,    x29,    10
sw                  x12,    1197(x31)
li                  x1,     0x9e7404f9
pv.cmpltu.sci.b     x25,    x1,     27
sw                  x25,    0(x31)
li                  x30,    0x5cb23fe3
li                  x15,    0xf8bffe76
pv.cmpleu.h         x7,     x30,    x15
sw                  x7,     88(x31)
li                  x0,     0xc4b72a34
li                  x30,    0x911cc246
pv.cmpleu.h         x15,    x0,     x30
sw                  x15,    910(x31)
li                  x16,    0x45ba78ee
li                  x7,     0xf5eb72b1
pv.cmpleu.h         x20,    x16,    x7
sw                  x20,    0(x31)
li                  x13,    0xc18f8226
li                  x1,     0x631b8409
pv.cmpleu.b         x12,    x13,    x1
sw                  x12,    400(x31)
li                  x13,    0xe76e1cd5
li                  x9,     0xe55872ab
pv.cmpleu.b         x11,    x13,    x9
sw                  x11,    1925(x31)
li                  x31,    0xf717cd3d
li                  x1,     0x7392be4a
pv.cmpleu.b         x5,     x31,    x1
sw                  x5,     0(x31)
li                  x13,    0x523b769
li                  x15,    0x6353d165
pv.cmpleu.sc.h      x17,    x13,    x15
sw                  x17,    98(x31)
li                  x9,     0x15fa3bfa
li                  x28,    0x2a7c2b4c
pv.cmpleu.sc.h      x6,     x9,     x28
sw                  x6,     0(x31)
li                  x22,    0xdea1f8ad
li                  x4,     0x71c91e3a
pv.cmpleu.sc.h      x25,    x22,    x4
sw                  x25,    0(x31)
li                  x31,    0x2cc1f400
li                  x2,     0x4d31219d
pv.cmpleu.sc.b      x12,    x31,    x2
sw                  x12,    717(x31)
li                  x22,    0xd949410f
li                  x17,    0x97d497f4
pv.cmpleu.sc.b      x4,     x22,    x17
sw                  x4,     0(x31)
li                  x7,     0x3ce3905e
li                  x31,    0x9624096
pv.cmpleu.sc.b      x1,     x7,     x31
sw                  x1,     0(x31)
li                  x11,    0x2d60e6af
pv.cmpleu.sci.h     x28,    x11,    23
sw                  x28,    1731(x31)
li                  x3,     0x9bdd7988
pv.cmpleu.sci.h     x30,    x3,     24
sw                  x30,    0(x31)
li                  x17,    0x745aa2c6
pv.cmpleu.sci.h     x20,    x17,    19
sw                  x20,    0(x31)
li                  x26,    0x3a09a031
pv.cmpleu.sci.b     x15,    x26,    11
sw                  x15,    0(x31)
li                  x31,    0x62100307
pv.cmpleu.sci.b     x12,    x31,    26
sw                  x12,    1555(x31)
li                  x20,    0x3dda6859
pv.cmpleu.sci.b     x18,    x20,    30
sw                  x18,    0(x31)
li                  x14,    0x4f992f8a
li                  x16,    0xce7c41f5
pv.shuffle.h        x8,     x14,    x16
sw                  x8,     1281(x31)
li                  x1,     0xe27c8d14
li                  x14,    0x99e09917
pv.shuffle.h        x16,    x1,     x14
sw                  x16,    324(x31)
li                  x15,    0x205c3ac8
li                  x22,    0x819dc3ab
pv.shuffle.h        x5,     x15,    x22
sw                  x5,     1596(x31)
li                  x17,    0xfa47a0dc
pv.shuffle.sci.h    x14,    x17,    3
sw                  x14,    0(x31)
li                  x2,     0x4aa048ef
pv.shuffle.sci.h    x11,    x2,     0
sw                  x11,    267(x31)
li                  x14,    0x30e8410a
pv.shuffle.sci.h    x7,     x14,    39
sw                  x7,     0(x31)
li                  x14,    0xf71a9b15
li                  x2,     0xf33b7e34
pv.shuffle.b        x19,    x14,    x2
sw                  x19,    0(x31)
li                  x18,    0xf342f507
li                  x5,     0x5a4ccabe
pv.shuffle.b        x7,     x18,    x5
sw                  x7,     542(x31)
li                  x11,    0x7e749394
li                  x5,     0x51067971
pv.shuffle.b        x6,     x11,    x5
sw                  x6,     0(x31)
li                  x17,    0x17202d10
pv.shuffleI0.sci.b  x30,    x17,    42
sw                  x30,    470(x31)
li                  x9,     0x576a88ba
pv.shuffleI0.sci.b  x2,     x9,     3
sw                  x2,     0(x31)
li                  x11,    0x451c33cb
pv.shuffleI0.sci.b  x8,     x11,    2
sw                  x8,     0(x31)
li                  x16,    0x3f4940
pv.shuffleI1.sci.b  x11,    x16,    23
sw                  x11,    870(x31)
li                  x9,     0x48961efe
pv.shuffleI1.sci.b  x9,     x9,     5
sw                  x9,     0(x31)
li                  x25,    0xd1dcf230
pv.shuffleI1.sci.b  x12,    x25,    43
sw                  x12,    0(x31)
li                  x9,     0x304b047e
pv.shuffleI2.sci.b  x2,     x9,     0
sw                  x2,     0(x31)
li                  x30,    0xc300f1c8
pv.shuffleI2.sci.b  x9,     x30,    29
sw                  x9,     0(x31)
li                  x16,    0x30d7fa1f
pv.shuffleI2.sci.b  x26,    x16,    19
sw                  x26,    1302(x31)
li                  x21,    0xeddcec2f
pv.shuffleI3.sci.b  x12,    x21,    50
sw                  x12,    0(x31)
li                  x9,     0x5436054f
pv.shuffleI3.sci.b  x21,    x9,     26
sw                  x21,    0(x31)
li                  x25,    0x986bd0e6
pv.shuffleI3.sci.b  x10,    x25,    27
sw                  x10,    794(x31)
li                  x26,    0x554c9957
li                  x20,    0x765bbc03
pv.shuffle2.h       x3,     x26,    x20
sw                  x3,     1009(x31)
li                  x28,    0x577cda6f
li                  x23,    0x783a7f50
pv.shuffle2.h       x28,    x28,    x23
sw                  x28,    1152(x31)
li                  x16,    0x47497ac0
li                  x25,    0xb6fa7482
pv.shuffle2.h       x29,    x16,    x25
sw                  x29,    317(x31)
li                  x15,    0x40b98f1c
li                  x6,     0x4da200a
pv.shuffle2.b       x9,     x15,    x6
sw                  x9,     1926(x31)
li                  x12,    0x56835b35
li                  x27,    0x63844125
pv.shuffle2.b       x5,     x12,    x27
sw                  x5,     544(x31)
li                  x1,     0xa87c721f
li                  x8,     0xe6d83c53
pv.shuffle2.b       x23,    x1,     x8
sw                  x23,    391(x31)
li                  x31,    0x6124f739
li                  x23,    0xd81c77c9
pv.pack.h           x4,     x31,    x23
sw                  x4,     770(x31)
li                  x25,    0x252e0406
li                  x24,    0x3a5f0a7e
pv.pack.h           x14,    x25,    x24
sw                  x14,    144(x31)
li                  x9,     0xcd5855f9
li                  x27,    0x30e7c63d
pv.pack.h           x13,    x9,     x27
sw                  x13,    11(x31)
li                  x4,     0x8f9dcfc
li                  x24,    0x9cd5975d
pv.packhi.b         x25,    x4,     x24
sw                  x25,    132(x31)
li                  x28,    0x3db20846
li                  x13,    0x84bb8de9
pv.packhi.b         x12,    x28,    x13
sw                  x12,    0(x31)
li                  x2,     0x202fae33
li                  x4,     0xba6ffd35
pv.packhi.b         x15,    x2,     x4
sw                  x15,    923(x31)
li                  x3,     0xa77f58df
li                  x18,    0xc304961c
pv.packlo.b         x15,    x3,     x18
sw                  x15,    1138(x31)
li                  x24,    0xd6dbc6e6
li                  x9,     0xf8e924b2
pv.packlo.b         x27,    x24,    x9
sw                  x27,    1613(x31)
li                  x16,    0x3a72c6c
li                  x0,     0x1e8ce15f
pv.packlo.b         x18,    x16,    x0
sw                  x18,    1301(x31)